In [2]:
print('hello')

hello

In [3]:
import os

os.getcwd()

'C:\\Users\\asus'

In [4]:
import os

os.listdir()

['-1.14-windows.xml',
 '.anaconda',
 '.arduinoIDE',
 '.conda',
 '.continuum',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.packettracer',
 '.vscode',
 '.vscode-shared',
 '01_Flight_Data_Inspection.ipynb',
 '3D Objects',
 'anaconda3',
 'anaconda_projects',
 'ansel',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'customer_shopping_behavior.csv',
 'Customer_Shopping_Behavior_Analysis.ipynb',
 'Documents',
 'Downloads',
 'edb_asp_bluefin_pg18.exe',
 'edb_pgagent_pg18.exe',
 'edb_pgbouncer.exe',
 'edb_psqlodbc.exe',
 'edb_psqlodbc.exe-20260919014652',
 'edb_psqlodbc.exe-20260919015348',
 'edb_psqlodbc.exe-20260919015407',
 'Favorites',
 'HR_Analytics.csv',
 'HR_Analytics_Cleaned.csv',
 'HR_Analytics_EDA.ipynb',
 'HR_Analytics_Final.csv',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf.cnpf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms.cnpf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms.cnpf',
 'ntuser.ini',
 'OneDrive',
 'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv',
 'pemhttpd.exe',
 'postgresql_18.exe',
 'PrintHood',
 'python 1',
 'Recent',
 'Retail-Sales-Analysis-SQL-Project--P1',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Videos']

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv")

C:\Users\asus\AppData\Local\Temp\ipykernel_4172\3210165706.py:1: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv")

In [7]:
df.shape

(539747, 110)

In [8]:
df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2025,1,1,1,3,2025-01-01,AA,19805,AA,N104NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025,1,1,2,4,2025-01-02,AA,19805,AA,N110AN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025,1,1,3,5,2025-01-03,AA,19805,AA,N106NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025,1,1,4,6,2025-01-04,AA,19805,AA,N117AN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025,1,1,5,7,2025-01-05,AA,19805,AA,N104NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 499.9 MB

In [10]:
df.columns.tolist()

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'Dest',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'CRSDepTime',
 'DepTime',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrTime',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'ArrivalDelayGroups',
 'ArrTimeBlk',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'DistanceGroup',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'TotalAddGTime',
 'LongestAddGTime',
 'DivAirportLandings',
 'DivReachedDest',
 'DivActualElapsedTime',
 'DivArrDelay',
 'DivDistance',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1WheelsOn',
 'Div1TotalGTime',
 'Div1LongestGTime',
 'Div1WheelsOff',
 'Div1TailNum',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3WheelsOn',
 'Div3TotalGTime',
 'Div3LongestGTime',
 'Div3WheelsOff',
 'Div3TailNum',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4WheelsOn',
 'Div4TotalGTime',
 'Div4LongestGTime',
 'Div4WheelsOff',
 'Div4TailNum',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5WheelsOn',
 'Div5TotalGTime',
 'Div5LongestGTime',
 'Div5WheelsOff',
 'Div5TailNum',
 'Unnamed: 109']

In [11]:
df.isna().sum().sort_values(ascending=False)

Div5WheelsOn        539747
Div5TotalGTime      539747
Div5LongestGTime    539747
Div5WheelsOff       539747
Div5TailNum         539747
                     ...
Diverted                 0
ArrTimeBlk               0
CRSElapsedTime           0
Distance                 0
DistanceGroup            0
Length: 110, dtype: int64

In [12]:
df.isna().mean().sort_values(ascending=False).head(20)

Div5WheelsOn        1.0
Div5TotalGTime      1.0
Div5LongestGTime    1.0
Div5WheelsOff       1.0
Div5TailNum         1.0
Div5Airport         1.0
Unnamed: 109        1.0
Div4TailNum         1.0
Div4WheelsOff       1.0
Div4LongestGTime    1.0
Div4TotalGTime      1.0
Div4WheelsOn        1.0
Div4AirportSeqID    1.0
Div4AirportID       1.0
Div5AirportID       1.0
Div5AirportSeqID    1.0
Div3WheelsOff       1.0
Div3LongestGTime    1.0
Div3TotalGTime      1.0
Div3WheelsOn        1.0
dtype: float64

In [13]:
important_cols = [
    "FlightDate",
    "Reporting_Airline",
    "Tail_Number",
    "Origin",
    "Dest",
    "DepDelay",
    "ArrDelay",
    "CarrierDelay",
    "WeatherDelay",
    "NASDelay",
    "SecurityDelay",
    "LateAircraftDelay",
    "Cancelled",
    "Diverted"
]

df[important_cols].isna().mean().sort_values(ascending=False)

WeatherDelay         0.818193
LateAircraftDelay    0.818193
SecurityDelay        0.818193
NASDelay             0.818193
CarrierDelay         0.818193
ArrDelay             0.032382
DepDelay             0.029501
Tail_Number          0.004687
FlightDate           0.000000
Reporting_Airline    0.000000
Dest                 0.000000
Origin               0.000000
Cancelled            0.000000
Diverted             0.000000
dtype: float64

In [14]:
df[df["ArrDelay"].isna()][
    ["Cancelled", "Diverted", "DepDelay", "ArrDelay"]
].head(10)

     Cancelled  Diverted  DepDelay  ArrDelay
53         0.0       1.0      -5.0       NaN
84         1.0       0.0       NaN       NaN
119        0.0       1.0       1.0       NaN
124        1.0       0.0       NaN       NaN
128        1.0       0.0       NaN       NaN
159        1.0       0.0       NaN       NaN
196        1.0       0.0       NaN       NaN
224        0.0       1.0     117.0       NaN
331        1.0       0.0       NaN       NaN
387        1.0       0.0       NaN       NaN

In [15]:
df[["Cancelled", "Diverted"]].sum()

Cancelled    16312.0
Diverted      1166.0
dtype: float64

In [16]:
df[["Cancelled", "Diverted"]].mean() * 100

Cancelled    3.022157
Diverted     0.216027
dtype: float64

In [17]:
df[["DepDelay", "ArrDelay"]].describe()

            DepDelay       ArrDelay
count  523824.000000  522269.000000
mean       10.340809       3.756614
std        54.328344      56.850884
min       -50.000000     -87.000000
25%        -6.000000     -18.000000
50%        -3.000000      -8.000000
75%         6.000000       7.000000
max      3298.000000    3282.000000

In [18]:
(df["DepDelay"] > 0).sum(), (df["ArrDelay"] > 0).sum()

(np.int64(177108), np.int64(172133))

In [19]:
dep_late_pct = (df["DepDelay"] > 0).mean() * 100
arr_late_pct = (df["ArrDelay"] > 0).mean() * 100

dep_late_pct, arr_late_pct

(np.float64(32.813151346834715), np.float64(31.89142320383439))

In [20]:
delay_causes = [
    "CarrierDelay",
    "WeatherDelay",
    "NASDelay",
    "SecurityDelay",
    "LateAircraftDelay"
]

df[delay_causes].notna().any(axis=1).sum()

np.int64(98130)

In [21]:
df[delay_causes].notna().sum().sort_values(ascending=False)

CarrierDelay         98130
WeatherDelay         98130
NASDelay             98130
SecurityDelay        98130
LateAircraftDelay    98130
dtype: int64

In [22]:
df[delay_causes].head(10)

   CarrierDelay  WeatherDelay  NASDelay  SecurityDelay  LateAircraftDelay
0           NaN           NaN       NaN            NaN                NaN
1           NaN           NaN       NaN            NaN                NaN
2           NaN           NaN       NaN            NaN                NaN
3           NaN           NaN       NaN            NaN                NaN
4           NaN           NaN       NaN            NaN                NaN
5           NaN           NaN       NaN            NaN                NaN
6           NaN           NaN       NaN            NaN                NaN
7           NaN           NaN       NaN            NaN                NaN
8           NaN           NaN       NaN            NaN                NaN
9           NaN           NaN       NaN            NaN                NaN

In [23]:
df.loc[0:9, ["FlightDate", "DepDelay", "ArrDelay", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]]

,FlightDate,DepDelay,ArrDelay,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2025-01-01,-3.0,-7.0,NaN,NaN,NaN,NaN,NaN
1,2025-01-02,-7.0,2.0,NaN,NaN,NaN,NaN,NaN
2,2025-01-03,-7.0,-17.0,NaN,NaN,NaN,NaN,NaN
3,2025-01-04,-7.0,-10.0,NaN,NaN,NaN,NaN,NaN
4,2025-01-05,-4.0,-7.0,NaN,NaN,NaN,NaN,NaN
5,2025-01-06,4.0,-8.0,NaN,NaN,NaN,NaN,NaN
6,2025-01-07,-5.0,-40.0,NaN,NaN,NaN,NaN,NaN
7,2025-01-08,-8.0,-52.0,NaN,NaN,NaN,NaN,NaN
8,2025-01-09,-5.0,-46.0,NaN,NaN,NaN,NaN,NaN
9,2025-01-10,0.0,-35.0,NaN,NaN,NaN,NaN,NaN

In [24]:
df[df["ArrDelay"] > 15][
    ["FlightDate", "DepDelay", "ArrDelay",
     "CarrierDelay", "WeatherDelay", "NASDelay",
     "SecurityDelay", "LateAircraftDelay"]
].head(10)

,FlightDate,DepDelay,ArrDelay,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
11,2025-01-12,204.0,245.0,204.0,0.0,41.0,0.0,0.0
25,2025-01-26,-6.0,25.0,0.0,0.0,25.0,0.0,0.0
61,2025-01-31,326.0,316.0,0.0,0.0,0.0,0.0,316.0
85,2025-01-27,155.0,122.0,122.0,0.0,0.0,0.0,0.0
98,2025-01-10,47.0,54.0,14.0,0.0,7.0,0.0,33.0
103,2025-01-17,555.0,535.0,0.0,0.0,0.0,0.0,535.0
105,2025-01-19,0.0,36.0,0.0,0.0,36.0,0.0,0.0
108,2025-01-22,70.0,44.0,44.0,0.0,0.0,0.0,0.0
111,2025-01-25,155.0,115.0,115.0,0.0,0.0,0.0,0.0
117,2025-01-31,397.0,377.0,172.0,0.0,0.0,0.0,205.0

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df["Reporting_Airline"].nunique(), df["Origin"].nunique(), df["Dest"].nunique()

(14, 329, 329)

In [27]:
df["Tail_Number"].nunique()

5612

In [28]:
df["Tail_Number"].value_counts().head(10)

Tail_Number
N478HA    300
N477HA    289
N486HA    289
N488HA    288
N483HA    285
N480HA    278
N492HA    277
N490HA    277
N491HA    277
N484HA    270
Name: count, dtype: int64

In [29]:
df["Flight_Number_Reporting_Airline"].nunique()

6390

In [30]:
df.isna().all().sum()

np.int64(25)

In [31]:
df.columns[df.isna().all()].tolist()

['Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3WheelsOn',
 'Div3TotalGTime',
 'Div3LongestGTime',
 'Div3WheelsOff',
 'Div3TailNum',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4WheelsOn',
 'Div4TotalGTime',
 'Div4LongestGTime',
 'Div4WheelsOff',
 'Div4TailNum',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5WheelsOn',
 'Div5TotalGTime',
 'Div5LongestGTime',
 'Div5WheelsOff',
 'Div5TailNum',
 'Unnamed: 109']

In [32]:
df_clean = df.copy()

In [33]:
df_clean = df_clean.dropna(axis=1, how="all")

In [34]:
df_clean.shape

(539747, 85)

In [35]:
df_clean.dtypes

Year                  int64
Quarter               int64
Month                 int64
DayofMonth            int64
DayOfWeek             int64
                     ...
Div2WheelsOn        float64
Div2TotalGTime      float64
Div2LongestGTime    float64
Div2WheelsOff       float64
Div2TailNum             str
Length: 85, dtype: object

In [36]:
df_clean[[
    "FlightDate",
    "Reporting_Airline",
    "Tail_Number",
    "Origin",
    "Dest",
    "DepTime",
    "ArrTime",
    "DepDelay",
    "ArrDelay",
    "Cancelled",
    "Diverted"
]].dtypes

FlightDate               str
Reporting_Airline        str
Tail_Number              str
Origin                   str
Dest                     str
DepTime              float64
ArrTime              float64
DepDelay             float64
ArrDelay             float64
Cancelled            float64
Diverted             float64
dtype: object

In [37]:
df_clean["FlightDate"] = pd.to_datetime(df_clean["FlightDate"])

In [38]:
df_clean["FlightDate"].dtype

dtype('<M8[us]')

In [39]:
df_clean[["DepTime", "ArrTime"]].head(10)

   DepTime  ArrTime
0    656.0   1013.0
1    652.0   1022.0
2    652.0   1003.0
3    653.0   1016.0
4    655.0   1013.0
5    703.0   1012.0
6    655.0    955.0
7    652.0    943.0
8    654.0    942.0
9    700.0   1000.0

In [40]:
df_clean["Reporting_Airline"].value_counts()

Reporting_Airline
WN    105307
DL     76306
AA     75088
OO     65036
UA     62007
YX     27833
MQ     21890
OH     21094
AS     18163
B6     17918
NK     17544
F9     15526
G4      9345
HA      6690
Name: count, dtype: int64

In [41]:
df_clean["Origin"].nunique(), df_clean["Dest"].nunique()

(329, 329)

In [42]:
df_clean[["Origin", "Dest"]].isna().sum()

Origin    0
Dest      0
dtype: int64

In [43]:
df_clean[df_clean["ArrDelay"].isna()][
    ["Cancelled", "Diverted", "DepDelay", "ArrDelay"]
].value_counts().head(10)

Series([], Name: count, dtype: int64)

In [44]:
df_clean[df_clean["ArrDelay"].isna()][
    ["Cancelled", "Diverted", "DepDelay", "ArrDelay"]
].head(10)

     Cancelled  Diverted  DepDelay  ArrDelay
53         0.0       1.0      -5.0       NaN
84         1.0       0.0       NaN       NaN
119        0.0       1.0       1.0       NaN
124        1.0       0.0       NaN       NaN
128        1.0       0.0       NaN       NaN
159        1.0       0.0       NaN       NaN
196        1.0       0.0       NaN       NaN
224        0.0       1.0     117.0       NaN
331        1.0       0.0       NaN       NaN
387        1.0       0.0       NaN       NaN

In [45]:
df_clean.loc[df_clean["ArrDelay"].isna(), ["Cancelled", "Diverted"]].sum()

Cancelled    16312.0
Diverted      1166.0
dtype: float64

In [46]:
df_clean[df_clean["DepDelay"].isna()][
    ["Cancelled", "Diverted", "DepDelay", "ArrDelay"]
].head(10)

     Cancelled  Diverted  DepDelay  ArrDelay
84         1.0       0.0       NaN       NaN
124        1.0       0.0       NaN       NaN
128        1.0       0.0       NaN       NaN
159        1.0       0.0       NaN       NaN
196        1.0       0.0       NaN       NaN
331        1.0       0.0       NaN       NaN
387        1.0       0.0       NaN       NaN
465        1.0       0.0       NaN       NaN
579        1.0       0.0       NaN       NaN
822        1.0       0.0       NaN       NaN

In [47]:
df_clean["DepDelay"].isna().sum()

np.int64(15923)

In [48]:
df_clean[
    (df_clean["Cancelled"] == 1) &
    (df_clean["DepDelay"].notna())
][["Cancelled", "Diverted", "DepDelay", "ArrDelay"]].head(10)

       Cancelled  Diverted  DepDelay  ArrDelay
418          1.0       0.0     380.0       NaN
816          1.0       0.0     199.0       NaN
3023         1.0       0.0      28.0       NaN
4090         1.0       0.0     500.0       NaN
5430         1.0       0.0     146.0       NaN
6393         1.0       0.0      -7.0       NaN
6797         1.0       0.0     178.0       NaN
8532         1.0       0.0       1.0       NaN
10288        1.0       0.0      -9.0       NaN
11769        1.0       0.0      -2.0       NaN

In [49]:
df_clean.loc[418, [
    "FlightDate",
    "Reporting_Airline",
    "Tail_Number",
    "Origin",
    "Dest",
    "CRSDepTime",
    "DepTime",
    "DepDelay",
    "CRSArrTime",
    "ArrTime",
    "ArrDelay",
    "Cancelled",
    "CancellationCode",
    "Diverted"
]]

FlightDate           2025-01-09 00:00:00
Reporting_Airline                     AA
Tail_Number                       N771AN
Origin                               DFW
Dest                                 HNL
CRSDepTime                           930
DepTime                           1550.0
DepDelay                           380.0
CRSArrTime                          1400
ArrTime                              NaN
ArrDelay                             NaN
Cancelled                            1.0
CancellationCode                       B
Diverted                             0.0
Name: 418, dtype: object

In [50]:
df_clean["CancellationCode"].value_counts(dropna=False)

CancellationCode
NaN    523435
B       14327
A        1635
C         342
D           8
Name: count, dtype: int64

In [51]:
df_clean["Tail_Number"].isna().sum()

np.int64(2530)

In [52]:
missing_tail_pct = df_clean["Tail_Number"].isna().mean() * 100
missing_tail_pct

np.float64(0.46873813101323397)

In [53]:
df_clean["DepDelay"].apply(
    lambda x: "Early" if x < 0 else "On Time" if x == 0 else "Late"
).value_counts()

DepDelay
Early      325311
Late       193031
On Time     21405
Name: count, dtype: int64

In [54]:
df_clean["DepDelay"].nlargest(10)

57434     3298.0
25469     3100.0
502118    2983.0
5333      2646.0
10583     2455.0
46288     2336.0
18614     2214.0
21553     2127.0
67391     2063.0
6139      1873.0
Name: DepDelay, dtype: float64

In [55]:
df_clean.loc[
    df_clean["DepDelay"].nlargest(10).index,
    [
        "FlightDate",
        "Reporting_Airline",
        "Tail_Number",
        "Origin",
        "Dest",
        "CRSDepTime",
        "DepTime",
        "DepDelay",
        "ArrDelay",
        "Cancelled",
        "Diverted"
    ]
]

,FlightDate,Reporting_Airline,Tail_Number,Origin,Dest,CRSDepTime,DepTime,DepDelay,ArrDelay,Cancelled,Diverted
57434,2025-01-28,AA,N747UW,IAH,DFW,1001,1659.0,3298.0,3282.0,0.0,0.0
25469,2025-01-15,AA,N751UW,MCI,ORD,700,1040.0,3100.0,NaN,1.0,0.0
502118,2025-01-03,MQ,N740MR,MLU,DFW,530,713.0,2983.0,2955.0,0.0,0.0
5333,2025-01-09,AA,N9015D,JAC,ORD,1247,853.0,2646.0,2680.0,0.0,0.0
10583,2025-01-13,AA,N886NN,CHS,CLT,650,2345.0,2455.0,2448.0,0.0,0.0
46288,2025-01-15,AA,N812AW,SDF,CLT,854,2350.0,2336.0,2310.0,0.0,0.0
18614,2025-01-23,AA,N815AW,RDU,PHL,815,2109.0,2214.0,2197.0,0.0,0.0
21553,2025-01-15,AA,N806AW,MFE,DFW,1123,2250.0,2127.0,2157.0,0.0,0.0
67391,2025-01-15,AA,N805NN,STL,CLT,936,1959.0,2063.0,2065.0,0.0,0.0
6139,2025-01-20,AA,N994AN,SDF,CLT,612,1325.0,1873.0,1856.0,0.0,0.0

In [56]:
df_clean[["DepDel15", "ArrDel15"]].value_counts(dropna=False)

DepDel15  ArrDel15
0.0       0.0         402781
1.0       1.0          73710
0.0       1.0          24420
1.0       0.0          21358
NaN       NaN          15923
0.0       NaN            963
1.0       NaN            592
Name: count, dtype: int64

In [57]:
(
    (df_clean["DepDelay"] >= 15) == (df_clean["DepDel15"] == 1)
).value_counts()

True    539747
Name: count, dtype: int64

In [58]:
df_clean["Route"] = df_clean["Origin"] + " → " + df_clean["Dest"]

In [59]:
df_clean["Route"].head()

0    JFK → LAX
1    JFK → LAX
2    JFK → LAX
3    JFK → LAX
4    JFK → LAX
Name: Route, dtype: str

In [60]:
df_clean["IsDelayedDeparture"] = df_clean["DepDel15"] == 1
df_clean["IsDelayedArrival"] = df_clean["ArrDel15"] == 1

In [61]:
df_clean[["IsDelayedDeparture", "IsDelayedArrival"]].head()

   IsDelayedDeparture  IsDelayedArrival
0               False             False
1               False             False
2               False             False
3               False             False
4               False             False

In [62]:
df_clean["IsDelayedDeparture"].value_counts(dropna=False)

IsDelayedDeparture
False    444087
True      95660
Name: count, dtype: int64

In [63]:
df_clean["IsDelayedArrival"].value_counts(dropna=False)

IsDelayedArrival
False    441617
True      98130
Name: count, dtype: int64

In [64]:
df_clean["IsDelayedDeparture"] = df_clean["DepDel15"].map({1.0: True, 0.0: False})
df_clean["IsDelayedArrival"] = df_clean["ArrDel15"].map({1.0: True, 0.0: False})

In [65]:
df_clean["IsDelayedDeparture"].value_counts(dropna=False)

IsDelayedDeparture
False    428164
True      95660
NaN       15923
Name: count, dtype: int64

In [66]:
df_clean["IsDelayedArrival"].value_counts(dropna=False)

IsDelayedArrival
False    424139
True      98130
NaN       17478
Name: count, dtype: int64

In [67]:
departure_delay_rate = (
    df_clean["IsDelayedDeparture"].mean() * 100
)

arrival_delay_rate = (
    df_clean["IsDelayedArrival"].mean() * 100
)

departure_delay_rate, arrival_delay_rate

(np.float64(18.261858944989157), np.float64(18.78916803409737))

In [68]:
df_clean["DelayRecovery"] = df_clean["DepDelay"] - df_clean["ArrDelay"]

In [69]:
df_clean[["DepDelay", "ArrDelay", "DelayRecovery"]].head(10)

   DepDelay  ArrDelay  DelayRecovery
0      -3.0      -7.0            4.0
1      -7.0       2.0           -9.0
2      -7.0     -17.0           10.0
3      -7.0     -10.0            3.0
4      -4.0      -7.0            3.0
5       4.0      -8.0           12.0
6      -5.0     -40.0           35.0
7      -8.0     -52.0           44.0
8      -5.0     -46.0           41.0
9       0.0     -35.0           35.0

In [70]:
df_clean["DelayRecovery"].describe()

count    522269.000000
mean          6.479328
std          15.288836
min        -231.000000
25%           0.000000
50%           8.000000
75%          15.000000
max         257.000000
Name: DelayRecovery, dtype: float64

In [71]:
df_clean["DelayRecovery"].apply(
    lambda x: "Recovered" if x > 0
    else "Same" if x == 0
    else "Additional Delay"
).value_counts()

DelayRecovery
Recovered           384328
Additional Delay    143810
Same                 11609
Name: count, dtype: int64

In [72]:
df_clean["RecoveryStatus"] = df_clean["DelayRecovery"].apply(
    lambda x: "Recovered" if x > 0
    else "Same" if x == 0
    else "Additional Delay" if pd.notna(x)
    else "Not Applicable"
)

In [73]:
df_clean["RecoveryStatus"].value_counts()

RecoveryStatus
Recovered           384328
Additional Delay    126332
Not Applicable       17478
Same                 11609
Name: count, dtype: int64

In [74]:
df_clean.shape

(539747, 90)

In [75]:
df_clean[[
    "FlightDate",
    "Route",
    "IsDelayedDeparture",
    "IsDelayedArrival",
    "DelayRecovery",
    "RecoveryStatus"
]].head()

,FlightDate,Route,IsDelayedDeparture,IsDelayedArrival,DelayRecovery,RecoveryStatus
0,2025-01-01,JFK → LAX,False,False,4.0,Recovered
1,2025-01-02,JFK → LAX,False,False,-9.0,Additional Delay
2,2025-01-03,JFK → LAX,False,False,10.0,Recovered
3,2025-01-04,JFK → LAX,False,False,3.0,Recovered
4,2025-01-05,JFK → LAX,False,False,3.0,Recovered

In [76]:
df_clean[[
    "FlightDate",
    "CRSDepTime",
    "DepTime",
    "CRSArrTime",
    "ArrTime"
]].head(10)

  FlightDate  CRSDepTime  DepTime  CRSArrTime  ArrTime
0 2025-01-01         659    656.0        1020   1013.0
1 2025-01-02         659    652.0        1020   1022.0
2 2025-01-03         659    652.0        1020   1003.0
3 2025-01-04         700    653.0        1026   1016.0
4 2025-01-05         659    655.0        1020   1013.0
5 2025-01-06         659    703.0        1020   1012.0
6 2025-01-07         700    655.0        1035    955.0
7 2025-01-08         700    652.0        1035    943.0
8 2025-01-09         659    654.0        1028    942.0
9 2025-01-10         700    700.0        1035   1000.0

In [77]:
df_clean[["DepTime", "ArrTime"]].isna().sum()

DepTime    15886
ArrTime    16580
dtype: int64

In [78]:
df_clean["DepTime"].dropna().astype(int).astype(str).str.zfill(4).head(20)

0     0656
1     0652
2     0652
3     0653
4     0655
5     0703
6     0655
7     0652
8     0654
9     0700
10    0652
11    1024
12    0656
13    0707
14    0653
15    0653
16    0654
17    0652
18    0651
19    0654
Name: DepTime, dtype: str

In [79]:
df_clean["ActualDeparture"] = pd.to_datetime(
    df_clean["FlightDate"].dt.strftime("%Y-%m-%d") + " " +
    df_clean["DepTime"].fillna(0).astype(int).astype(str).str.zfill(4),
    format="%Y-%m-%d %H%M",
    errors="coerce"
)

In [80]:
df_clean[["FlightDate", "DepTime", "ActualDeparture"]].head(10)

  FlightDate  DepTime     ActualDeparture
0 2025-01-01    656.0 2025-01-01 06:56:00
1 2025-01-02    652.0 2025-01-02 06:52:00
2 2025-01-03    652.0 2025-01-03 06:52:00
3 2025-01-04    653.0 2025-01-04 06:53:00
4 2025-01-05    655.0 2025-01-05 06:55:00
5 2025-01-06    703.0 2025-01-06 07:03:00
6 2025-01-07    655.0 2025-01-07 06:55:00
7 2025-01-08    652.0 2025-01-08 06:52:00
8 2025-01-09    654.0 2025-01-09 06:54:00
9 2025-01-10    700.0 2025-01-10 07:00:00

In [81]:
df_clean.loc[df_clean["DepTime"].isna(), "ActualDeparture"] = pd.NaT

In [82]:
df_clean["ActualDeparture"].isna().sum()

np.int64(15919)

In [83]:
df_clean[["CRSArrTime", "ArrTime"]].describe()

          CRSArrTime        ArrTime
count  539747.000000  523167.000000
mean     1502.662084    1482.305705
std       502.478468     520.043174
min         1.000000       1.000000
25%      1117.000000    1106.000000
50%      1524.000000    1515.000000
75%      1924.000000    1917.000000
max      2359.000000    2400.000000

In [84]:
df_clean["ArrTime"].eq(2400).sum()

np.int64(245)

In [85]:
df_clean["ActualArrival"] = pd.NaT

# Normal arrival times
mask_normal = df_clean["ArrTime"].notna() & (df_clean["ArrTime"] != 2400)

df_clean.loc[mask_normal, "ActualArrival"] = pd.to_datetime(
    df_clean.loc[mask_normal, "FlightDate"].dt.strftime("%Y-%m-%d") + " " +
    df_clean.loc[mask_normal, "ArrTime"].astype(int).astype(str).str.zfill(4),
    format="%Y-%m-%d %H%M",
    errors="coerce"
)

# Midnight (2400) = next day at 00:00
mask_midnight = df_clean["ArrTime"] == 2400

df_clean.loc[mask_midnight, "ActualArrival"] = (
    df_clean.loc[mask_midnight, "FlightDate"] + pd.Timedelta(days=1)
)

In [86]:
df_clean[
    ["FlightDate", "DepTime", "ArrTime", "ActualDeparture", "ActualArrival"]
].head(10)

  FlightDate  DepTime  ArrTime     ActualDeparture       ActualArrival
0 2025-01-01    656.0   1013.0 2025-01-01 06:56:00 2025-01-01 10:13:00
1 2025-01-02    652.0   1022.0 2025-01-02 06:52:00 2025-01-02 10:22:00
2 2025-01-03    652.0   1003.0 2025-01-03 06:52:00 2025-01-03 10:03:00
3 2025-01-04    653.0   1016.0 2025-01-04 06:53:00 2025-01-04 10:16:00
4 2025-01-05    655.0   1013.0 2025-01-05 06:55:00 2025-01-05 10:13:00
5 2025-01-06    703.0   1012.0 2025-01-06 07:03:00 2025-01-06 10:12:00
6 2025-01-07    655.0    955.0 2025-01-07 06:55:00 2025-01-07 09:55:00
7 2025-01-08    652.0    943.0 2025-01-08 06:52:00 2025-01-08 09:43:00
8 2025-01-09    654.0    942.0 2025-01-09 06:54:00 2025-01-09 09:42:00
9 2025-01-10    700.0   1000.0 2025-01-10 07:00:00 2025-01-10 10:00:00

In [87]:
df_clean[df_clean["ArrTime"] == 2400][
    ["FlightDate", "ArrTime", "ActualArrival"]
].head()

     FlightDate  ArrTime ActualArrival
2611 2025-01-26   2400.0    2025-01-27
3334 2025-01-02   2400.0    2025-01-03
3565 2025-01-01   2400.0    2025-01-02
4360 2025-01-30   2400.0    2025-01-31
4979 2025-01-04   2400.0    2025-01-05

In [88]:
overnight_check = (
    df_clean["ActualArrival"].notna() &
    df_clean["ActualDeparture"].notna() &
    (df_clean["ActualArrival"] < df_clean["ActualDeparture"])
)

overnight_check.sum()

np.int64(18804)

In [89]:
df_clean.loc[overnight_check, "ActualArrival"] += pd.Timedelta(days=1)

In [90]:
(
    df_clean["ActualArrival"].notna() &
    df_clean["ActualDeparture"].notna() &
    (df_clean["ActualArrival"] < df_clean["ActualDeparture"])
).sum()

np.int64(0)

In [91]:
df_clean[[
    "FlightDate",
    "Tail_Number",
    "Origin",
    "Dest",
    "ActualDeparture",
    "ActualArrival"
]].sample(10, random_state=42)

,FlightDate,Tail_Number,Origin,Dest,ActualDeparture,ActualArrival
212981,2025-01-29,N705SK,ORD,BNA,2025-01-29 17:27:00,2025-01-29 18:53:00
82762,2025-01-13,N713AL,SEA,PHX,2025-01-13 12:52:00,2025-01-13 16:28:00
415741,2025-01-20,N370NB,MSP,DFW,2025-01-20 10:39:00,2025-01-20 12:57:00
371245,2025-01-17,N8879Q,BWI,DAL,2025-01-17 09:03:00,2025-01-17 11:15:00
493974,2025-01-18,279NV,ABE,SFB,2025-01-18 06:47:00,2025-01-18 09:34:00
388581,2025-01-04,N401YX,CMH,DCA,2025-01-04 17:32:00,2025-01-04 18:34:00
505828,2025-01-23,N280NN,PHX,RDM,2025-01-23 21:23:00,2025-01-23 23:07:00
15739,2025-01-16,N703UW,MIA,OMA,2025-01-16 19:22:00,2025-01-16 22:02:00
497448,2025-01-28,N494HA,OGG,HNL,2025-01-28 10:29:00,2025-01-28 11:18:00
349906,2025-01-15,N8693A,HOU,SJC,2025-01-15 09:57:00,2025-01-15 11:57:00

In [92]:
df_clean[[
    "ActualDeparture",
    "ActualArrival"
]].isna().sum()

ActualDeparture    15919
ActualArrival      16580
dtype: int64

In [93]:
df_clean = df_clean.sort_values(
    ["Tail_Number", "ActualDeparture"]
).reset_index(drop=True)

In [94]:
df_clean[df_clean["Tail_Number"] == "N705SK"][
    [
        "FlightDate",
        "Tail_Number",
        "Origin",
        "Dest",
        "ActualDeparture",
        "ActualArrival",
        "DepDelay",
        "ArrDelay"
    ]
].head(15)

,FlightDate,Tail_Number,Origin,Dest,ActualDeparture,ActualArrival,DepDelay,ArrDelay
312039,2025-01-01,N705SK,PVU,PHX,2025-01-01 11:04:00,2025-01-01 12:39:00,154.0,143.0
312040,2025-01-01,N705SK,PHX,BUR,2025-01-01 15:21:00,2025-01-01 15:39:00,-8.0,-26.0
312041,2025-01-01,N705SK,BUR,PHX,2025-01-01 16:25:00,2025-01-01 18:54:00,-10.0,-20.0
312042,2025-01-01,N705SK,PHX,OKC,2025-01-01 19:53:00,2025-01-01 23:02:00,-6.0,-13.0
312043,2025-01-02,N705SK,OKC,PHX,2025-01-02 08:24:00,2025-01-02 10:22:00,-9.0,12.0
312044,2025-01-02,N705SK,PHX,SGU,2025-01-02 11:25:00,2025-01-02 13:07:00,-5.0,3.0
312045,2025-01-02,N705SK,SGU,DFW,2025-01-02 13:38:00,2025-01-02 16:55:00,4.0,-18.0
312046,2025-01-02,N705SK,DFW,HRL,2025-01-02 17:42:00,NaT,-10.0,NaN
312047,2025-01-02,N705SK,DFW,LAW,2025-01-02 23:29:00,2025-01-03 00:28:00,35.0,36.0
312048,2025-01-03,N705SK,LAW,DFW,2025-01-03 04:51:00,2025-01-03 05:54:00,-9.0,-12.0
312049,2025-01-03,N705SK,DFW,ICT,2025-01-03 07:06:00,2025-01-03 08:47:00,-8.0,-1.0
312050,2025-01-03,N705SK,ICT,DFW,2025-01-03 09:09:00,2025-01-03 10:48:00,-9.0,2.0
312051,2025-01-03,N705SK,DFW,SAF,2025-01-03 11:24:00,2025-01-03 12:11:00,17.0,5.0
312052,2025-01-03,N705SK,SAF,DFW,2025-01-03 12:43:00,2025-01-03 15:23:00,4.0,-8.0
312053,2025-01-03,N705SK,DFW,BRO,2025-01-03 15:57:00,2025-01-03 17:39:00,12.0,11.0

In [95]:
df_clean["PreviousArrival"] = (
    df_clean.groupby("Tail_Number")["ActualArrival"].shift(1)
)

df_clean["PreviousDest"] = (
    df_clean.groupby("Tail_Number")["Dest"].shift(1)
)

df_clean["PreviousArrDelay"] = (
    df_clean.groupby("Tail_Number")["ArrDelay"].shift(1)
)

In [96]:
df_clean[df_clean["Tail_Number"] == "N705SK"][
    [
        "Tail_Number",
        "Origin",
        "Dest",
        "ActualDeparture",
        "ActualArrival",
        "ArrDelay",
        "PreviousDest",
        "PreviousArrival",
        "PreviousArrDelay"
    ]
].head(15)

,Tail_Number,Origin,Dest,ActualDeparture,ActualArrival,ArrDelay,PreviousDest,PreviousArrival,PreviousArrDelay
312039,N705SK,PVU,PHX,2025-01-01 11:04:00,2025-01-01 12:39:00,143.0,NaN,NaT,NaN
312040,N705SK,PHX,BUR,2025-01-01 15:21:00,2025-01-01 15:39:00,-26.0,PHX,2025-01-01 12:39:00,143.0
312041,N705SK,BUR,PHX,2025-01-01 16:25:00,2025-01-01 18:54:00,-20.0,BUR,2025-01-01 15:39:00,-26.0
312042,N705SK,PHX,OKC,2025-01-01 19:53:00,2025-01-01 23:02:00,-13.0,PHX,2025-01-01 18:54:00,-20.0
312043,N705SK,OKC,PHX,2025-01-02 08:24:00,2025-01-02 10:22:00,12.0,OKC,2025-01-01 23:02:00,-13.0
312044,N705SK,PHX,SGU,2025-01-02 11:25:00,2025-01-02 13:07:00,3.0,PHX,2025-01-02 10:22:00,12.0
312045,N705SK,SGU,DFW,2025-01-02 13:38:00,2025-01-02 16:55:00,-18.0,SGU,2025-01-02 13:07:00,3.0
312046,N705SK,DFW,HRL,2025-01-02 17:42:00,NaT,NaN,DFW,2025-01-02 16:55:00,-18.0
312047,N705SK,DFW,LAW,2025-01-02 23:29:00,2025-01-03 00:28:00,36.0,HRL,NaT,NaN
312048,N705SK,LAW,DFW,2025-01-03 04:51:00,2025-01-03 05:54:00,-12.0,LAW,2025-01-03 00:28:00,36.0
312049,N705SK,DFW,ICT,2025-01-03 07:06:00,2025-01-03 08:47:00,-1.0,DFW,2025-01-03 05:54:00,-12.0
312050,N705SK,ICT,DFW,2025-01-03 09:09:00,2025-01-03 10:48:00,2.0,ICT,2025-01-03 08:47:00,-1.0
312051,N705SK,DFW,SAF,2025-01-03 11:24:00,2025-01-03 12:11:00,5.0,DFW,2025-01-03 10:48:00,2.0
312052,N705SK,SAF,DFW,2025-01-03 12:43:00,2025-01-03 15:23:00,-8.0,SAF,2025-01-03 12:11:00,5.0
312053,N705SK,DFW,BRO,2025-01-03 15:57:00,2025-01-03 17:39:00,11.0,DFW,2025-01-03 15:23:00,-8.0

In [97]:
df_clean["TurnaroundMinutes"] = (
    df_clean["ActualDeparture"] - df_clean["PreviousArrival"]
).dt.total_seconds() / 60

In [98]:
df_clean[df_clean["Tail_Number"] == "N705SK"][
    [
        "Tail_Number",
        "Origin",
        "Dest",
        "PreviousArrival",
        "ActualDeparture",
        "TurnaroundMinutes",
        "PreviousArrDelay",
        "DepDelay"
    ]
].head(15)

,Tail_Number,Origin,Dest,PreviousArrival,ActualDeparture,TurnaroundMinutes,PreviousArrDelay,DepDelay
312039,N705SK,PVU,PHX,NaT,2025-01-01 11:04:00,NaN,NaN,154.0
312040,N705SK,PHX,BUR,2025-01-01 12:39:00,2025-01-01 15:21:00,162.0,143.0,-8.0
312041,N705SK,BUR,PHX,2025-01-01 15:39:00,2025-01-01 16:25:00,46.0,-26.0,-10.0
312042,N705SK,PHX,OKC,2025-01-01 18:54:00,2025-01-01 19:53:00,59.0,-20.0,-6.0
312043,N705SK,OKC,PHX,2025-01-01 23:02:00,2025-01-02 08:24:00,562.0,-13.0,-9.0
312044,N705SK,PHX,SGU,2025-01-02 10:22:00,2025-01-02 11:25:00,63.0,12.0,-5.0
312045,N705SK,SGU,DFW,2025-01-02 13:07:00,2025-01-02 13:38:00,31.0,3.0,4.0
312046,N705SK,DFW,HRL,2025-01-02 16:55:00,2025-01-02 17:42:00,47.0,-18.0,-10.0
312047,N705SK,DFW,LAW,NaT,2025-01-02 23:29:00,NaN,NaN,35.0
312048,N705SK,LAW,DFW,2025-01-03 00:28:00,2025-01-03 04:51:00,263.0,36.0,-9.0
312049,N705SK,DFW,ICT,2025-01-03 05:54:00,2025-01-03 07:06:00,72.0,-12.0,-8.0
312050,N705SK,ICT,DFW,2025-01-03 08:47:00,2025-01-03 09:09:00,22.0,-1.0,-9.0
312051,N705SK,DFW,SAF,2025-01-03 10:48:00,2025-01-03 11:24:00,36.0,2.0,17.0
312052,N705SK,SAF,DFW,2025-01-03 12:11:00,2025-01-03 12:43:00,32.0,5.0,4.0
312053,N705SK,DFW,BRO,2025-01-03 15:23:00,2025-01-03 15:57:00,34.0,-8.0,12.0

In [99]:
df_clean["TurnaroundMinutes"].describe()

count    517543.000000
mean        287.366824
std         738.241703
min       -1418.000000
25%          55.000000
50%          78.000000
75%         378.000000
max       40364.000000
Name: TurnaroundMinutes, dtype: float64

In [100]:
df_clean["TurnaroundMinutes"].quantile(
    [0.10, 0.25, 0.50, 0.75, 0.90]
)

0.10     42.0
0.25     55.0
0.50     78.0
0.75    378.0
0.90    697.0
Name: TurnaroundMinutes, dtype: float64

In [101]:
df_clean[df_clean["TurnaroundMinutes"] < 0][
    [
        "FlightDate",
        "Tail_Number",
        "Origin",
        "Dest",
        "PreviousDest",
        "PreviousArrival",
        "ActualDeparture",
        "TurnaroundMinutes"
    ]
].head(10)

,FlightDate,Tail_Number,Origin,Dest,PreviousDest,PreviousArrival,ActualDeparture,TurnaroundMinutes
116,2025-01-24,189NV,FSD,FLL,FLL,2025-01-24 15:04:00,2025-01-24 12:59:00,-125.0
1152,2025-01-04,206NV,PGD,AVL,AVL,2025-01-04 01:16:00,2025-01-04 00:09:00,-67.0
1219,2025-01-05,207NV,IND,FLL,IND,2025-01-05 11:50:00,2025-01-05 10:07:00,-103.0
1842,2025-01-02,220NV,RAP,LAS,AZA,2025-01-02 14:33:00,2025-01-02 12:32:00,-121.0
1854,2025-01-05,220NV,LAS,SCK,CVG,2025-01-05 16:00:00,2025-01-05 13:10:00,-170.0
2612,2025-01-09,239NV,LAS,PVU,MFR,2025-01-09 10:27:00,2025-01-09 10:10:00,-17.0
2613,2025-01-09,239NV,MFR,SNA,PVU,2025-01-09 12:31:00,2025-01-09 11:15:00,-76.0
2721,2025-01-06,244NV,CVG,JAX,JAX,2025-01-06 16:23:00,2025-01-06 15:05:00,-78.0
2722,2025-01-06,244NV,JAX,CVG,JAX,2025-01-06 17:47:00,2025-01-06 17:10:00,-37.0
2723,2025-01-06,244NV,JAX,IAD,CVG,2025-01-06 19:06:00,2025-01-06 18:27:00,-39.0

In [102]:
(df_clean["TurnaroundMinutes"] < 0).sum()

np.int64(1801)

In [103]:
valid_connection = (
    df_clean["PreviousArrival"].notna() &
    df_clean["ActualDeparture"].notna() &
    (df_clean["PreviousDest"] == df_clean["Origin"]) &
    (df_clean["PreviousArrival"] <= df_clean["ActualDeparture"])
)

In [104]:
valid_connection.sum()

np.int64(505050)

In [105]:
valid_connection.mean() * 100

np.float64(93.57161781353115)

In [106]:
df_clean["ValidAircraftConnection"] = valid_connection

df_clean["ValidTurnaroundMinutes"] = df_clean["TurnaroundMinutes"].where(
    df_clean["ValidAircraftConnection"]
)

In [107]:
df_clean["ValidTurnaroundMinutes"].describe()

count    505050.000000
mean        263.634616
std         601.973118
min           0.000000
25%          55.000000
50%          77.000000
75%         343.000000
max       40364.000000
Name: ValidTurnaroundMinutes, dtype: float64

In [108]:
df_clean["ValidTurnaroundMinutes"].quantile(
    [0.10, 0.25, 0.50, 0.75, 0.90]
)

0.10     42.0
0.25     55.0
0.50     77.0
0.75    343.0
0.90    672.0
Name: ValidTurnaroundMinutes, dtype: float64

In [109]:
df_clean["TurnaroundBucket"] = pd.cut(
    df_clean["ValidTurnaroundMinutes"],
    bins=[0, 30, 60, 90, 120, 180, 360, float("inf")],
    labels=[
        "0-30 min",
        "31-60 min",
        "61-90 min",
        "91-120 min",
        "121-180 min",
        "181-360 min",
        "360+ min"
    ],
    include_lowest=True
)

In [110]:
df_clean["TurnaroundBucket"].value_counts().sort_index()

TurnaroundBucket
0-30 min        11439
31-60 min      150361
61-90 min      134952
91-120 min      42184
121-180 min     22838
181-360 min     19400
360+ min       123876
Name: count, dtype: int64

In [111]:
df_clean["PreviousArrDel15"] = (
    df_clean.groupby("Tail_Number")["ArrDel15"].shift(1)
)

In [112]:
df_clean[[
    "Tail_Number",
    "PreviousArrDelay",
    "PreviousArrDel15",
    "DepDel15",
    "TurnaroundBucket"
]].head(15)

   Tail_Number  PreviousArrDelay  PreviousArrDel15  DepDel15 TurnaroundBucket
0        188NV               NaN               NaN       0.0              NaN
1        188NV             -32.0               0.0       0.0        61-90 min
2        188NV             -17.0               0.0       0.0         360+ min
3        188NV             -21.0               0.0       0.0        61-90 min
4        188NV             -21.0               0.0       0.0        61-90 min
5        188NV               1.0               0.0       1.0        61-90 min
6        188NV              15.0               1.0       1.0        61-90 min
7        188NV              31.0               1.0       1.0        31-60 min
8        188NV              45.0               1.0       0.0         360+ min
9        188NV             -11.0               0.0       0.0        31-60 min
10       188NV              29.0               1.0       1.0        61-90 min
11       188NV              65.0               1.0       1.0        31-60 min
12       188NV              25.0               1.0       0.0         360+ min
13       188NV              -5.0               0.0       0.0        31-60 min
14       188NV             -32.0               0.0       0.0        61-90 min

In [113]:
propagation_analysis = (
    df_clean[
        df_clean["ValidAircraftConnection"] &
        df_clean["PreviousArrDel15"].notna() &
        df_clean["DepDel15"].notna()
    ]
    .groupby(["TurnaroundBucket", "PreviousArrDel15"])["DepDel15"]
    .agg(
        flights="count",
        delayed_departures="sum",
        departure_delay_rate="mean"
    )
    .reset_index()
)

In [114]:
propagation_analysis

,TurnaroundBucket,PreviousArrDel15,flights,delayed_departures,departure_delay_rate
0,0-30 min,0.0,5850,238.0,0.040684
1,0-30 min,1.0,5538,3853.0,0.695739
2,31-60 min,0.0,114224,6146.0,0.053807
3,31-60 min,1.0,35908,25855.0,0.720035
4,61-90 min,0.0,121003,9037.0,0.074684
5,61-90 min,1.0,13844,9927.0,0.717062
6,91-120 min,0.0,38610,6546.0,0.169542
7,91-120 min,1.0,3537,2026.0,0.572802
8,121-180 min,0.0,19869,5288.0,0.266143
9,121-180 min,1.0,2939,1413.0,0.480776
10,181-360 min,0.0,14169,2983.0,0.210530
11,181-360 min,1.0,5167,1078.0,0.208632
12,360+ min,0.0,98014,10591.0,0.108056
13,360+ min,1.0,25674,4560.0,0.177612

In [115]:
propagation_pivot = propagation_analysis.pivot(
    index="TurnaroundBucket",
    columns="PreviousArrDel15",
    values="departure_delay_rate"
)

propagation_pivot

PreviousArrDel15       0.0       1.0
TurnaroundBucket
0-30 min          0.040684  0.695739
31-60 min         0.053807  0.720035
61-90 min         0.074684  0.717062
91-120 min        0.169542  0.572802
121-180 min       0.266143  0.480776
181-360 min       0.210530  0.208632
360+ min          0.108056  0.177612

In [116]:
propagation_pivot["PropagationLift"] = (
    propagation_pivot[1] - propagation_pivot[0]
)

In [117]:
propagation_pivot

PreviousArrDel15       0.0       1.0  PropagationLift
TurnaroundBucket
0-30 min          0.040684  0.695739         0.655055
31-60 min         0.053807  0.720035         0.666228
61-90 min         0.074684  0.717062         0.642377
91-120 min        0.169542  0.572802         0.403260
121-180 min       0.266143  0.480776         0.214633
181-360 min       0.210530  0.208632        -0.001898
360+ min          0.108056  0.177612         0.069556

In [118]:
df_clean[
    df_clean["ValidAircraftConnection"] &
    df_clean["PreviousArrDelay"].notna() &
    df_clean["DepDelay"].notna()
][[
    "PreviousArrDelay",
    "DepDelay",
    "TurnaroundMinutes"
]].describe()

       PreviousArrDelay       DepDelay  TurnaroundMinutes
count     504346.000000  504346.000000      504346.000000
mean           2.374449       8.544910         263.502381
std           49.341814      43.405607         601.802027
min          -83.000000     -50.000000           0.000000
25%          -18.000000      -7.000000          55.000000
50%           -8.000000      -3.000000          77.000000
75%            6.000000       6.000000         343.000000
max         3282.000000    3298.000000       40364.000000

In [119]:
df_clean["PreviousDelayBucket"] = pd.cut(
    df_clean["PreviousArrDelay"],
    bins=[-float("inf"), 0, 15, 30, 60, 120, float("inf")],
    labels=[
        "Early/On Time",
        "1-14 min",
        "15-30 min",
        "31-60 min",
        "61-120 min",
        "120+ min"
    ]
)

In [120]:
df_clean["PreviousDelayBucket"].value_counts().sort_index()

PreviousDelayBucket
Early/On Time    348474
1-14 min          76934
15-30 min         33409
31-60 min         28442
61-120 min        19268
120+ min          13230
Name: count, dtype: int64

In [121]:
delay_magnitude_analysis = (
    df_clean[
        df_clean["ValidAircraftConnection"] &
        df_clean["PreviousDelayBucket"].notna() &
        df_clean["DepDel15"].notna()
    ]
    .groupby("PreviousDelayBucket")["DepDel15"]
    .agg(
        flights="count",
        delayed_departures="sum",
        departure_delay_rate="mean"
    )
    .reset_index()
)

In [122]:
delay_magnitude_analysis

  PreviousDelayBucket  flights  delayed_departures  departure_delay_rate
0       Early/On Time   340063             28727.0              0.084476
1            1-14 min    74865             13007.0              0.173739
2           15-30 min    32384             13207.0              0.407825
3           31-60 min    27406             16110.0              0.587827
4          61-120 min    18258             11598.0              0.635228
5            120+ min    11370              6892.0              0.606157

In [123]:
propagation_matrix = (
    df_clean[
        df_clean["ValidAircraftConnection"] &
        df_clean["PreviousDelayBucket"].notna() &
        df_clean["TurnaroundBucket"].notna() &
        df_clean["DepDel15"].notna()
    ]
    .groupby(
        ["TurnaroundBucket", "PreviousDelayBucket"]
    )["DepDel15"]
    .mean()
    .reset_index(name="departure_delay_rate")
)

In [124]:
propagation_matrix

   TurnaroundBucket PreviousDelayBucket  departure_delay_rate
0          0-30 min       Early/On Time              0.063474
1          0-30 min            1-14 min              0.022995
2          0-30 min           15-30 min              0.316404
3          0-30 min           31-60 min              0.827649
4          0-30 min          61-120 min              0.946916
5          0-30 min            120+ min              0.969456
6         31-60 min       Early/On Time              0.034230
7         31-60 min            1-14 min              0.119104
8         31-60 min           15-30 min              0.506971
9         31-60 min           31-60 min              0.843057
10        31-60 min          61-120 min              0.925937
11        31-60 min            120+ min              0.911651
12        61-90 min       Early/On Time              0.048809
13        61-90 min            1-14 min              0.280825
14        61-90 min           15-30 min              0.615111
15        61-90 min           31-60 min              0.779712
16        61-90 min          61-120 min              0.835418
17        61-90 min            120+ min              0.803484
18       91-120 min       Early/On Time              0.147749
19       91-120 min            1-14 min              0.396772
20       91-120 min           15-30 min              0.534646
21       91-120 min           31-60 min              0.581984
22       91-120 min          61-120 min              0.598837
23       91-120 min            120+ min              0.639013
24      121-180 min       Early/On Time              0.253789
25      121-180 min            1-14 min              0.360431
26      121-180 min           15-30 min              0.437126
27      121-180 min           31-60 min              0.470291
28      121-180 min          61-120 min              0.595707
29      121-180 min            120+ min              0.474747
30      181-360 min       Early/On Time              0.204977
31      181-360 min            1-14 min              0.235689
32      181-360 min           15-30 min              0.226636
33      181-360 min           31-60 min              0.198883
34      181-360 min          61-120 min              0.192130
35      181-360 min            120+ min              0.221381
36         360+ min       Early/On Time              0.103625
37         360+ min            1-14 min              0.129531
38         360+ min           15-30 min              0.146017
39         360+ min           31-60 min              0.156496
40         360+ min          61-120 min              0.203321
41         360+ min            120+ min              0.267546

In [125]:
propagation_matrix = (
    df_clean[
        df_clean["ValidAircraftConnection"] &
        df_clean["PreviousDelayBucket"].notna() &
        df_clean["TurnaroundBucket"].notna() &
        df_clean["DepDel15"].notna()
    ]
    .groupby(
        ["TurnaroundBucket", "PreviousDelayBucket"]
    )["DepDel15"]
    .agg(
        flights="count",
        delayed_departures="sum",
        departure_delay_rate="mean"
    )
    .reset_index()
)

In [126]:
propagation_matrix

,TurnaroundBucket,PreviousDelayBucket,flights,delayed_departures,departure_delay_rate
0,0-30 min,Early/On Time,2694,171.0,0.063474
1,0-30 min,1-14 min,3305,76.0,0.022995
2,0-30 min,15-30 min,1713,542.0,0.316404
3,0-30 min,31-60 min,1642,1359.0,0.827649
4,0-30 min,61-120 min,1281,1213.0,0.946916
5,0-30 min,120+ min,753,730.0,0.969456
6,31-60 min,Early/On Time,85189,2916.0,0.034230
7,31-60 min,1-14 min,30402,3621.0,0.119104
8,31-60 min,15-30 min,13269,6727.0,0.506971
9,31-60 min,31-60 min,10953,9234.0,0.843057
10,31-60 min,61-120 min,6697,6201.0,0.925937
11,31-60 min,120+ min,3622,3302.0,0.911651
12,61-90 min,Early/On Time,107051,5225.0,0.048809
13,61-90 min,1-14 min,14493,4070.0,0.280825
14,61-90 min,15-30 min,5347,3289.0,0.615111
15,61-90 min,31-60 min,3963,3090.0,0.779712
16,61-90 min,61-120 min,2558,2137.0,0.835418
17,61-90 min,120+ min,1435,1153.0,0.803484
18,91-120 min,Early/On Time,35161,5195.0,0.147749
19,91-120 min,1-14 min,3594,1426.0,0.396772
20,91-120 min,15-30 min,1270,679.0,0.534646
21,91-120 min,31-60 min,988,575.0,0.581984
22,91-120 min,61-120 min,688,412.0,0.598837
23,91-120 min,120+ min,446,285.0,0.639013
24,121-180 min,Early/On Time,17550,4454.0,0.253789
25,121-180 min,1-14 min,2411,869.0,0.360431
26,121-180 min,15-30 min,1002,438.0,0.437126
27,121-180 min,31-60 min,791,372.0,0.470291
28,121-180 min,61-120 min,559,333.0,0.595707
29,121-180 min,120+ min,495,235.0,0.474747
30,181-360 min,Early/On Time,11733,2405.0,0.204977
31,181-360 min,1-14 min,2533,597.0,0.235689
32,181-360 min,15-30 min,1284,291.0,0.226636
33,181-360 min,31-60 min,1433,285.0,0.198883
34,181-360 min,61-120 min,1296,249.0,0.192130
35,181-360 min,120+ min,1057,234.0,0.221381
36,360+ min,Early/On Time,80685,8361.0,0.103625
37,360+ min,1-14 min,18127,2348.0,0.129531
38,360+ min,15-30 min,8499,1241.0,0.146017
39,360+ min,31-60 min,7636,1195.0,0.156496
40,360+ min,61-120 min,5179,1053.0,0.203321
41,360+ min,120+ min,3562,953.0,0.267546

In [127]:
df_clean["DelayVsTurnaround"] = (
    df_clean["PreviousArrDelay"] - df_clean["TurnaroundMinutes"]
)

In [128]:
df_clean[
    df_clean["ValidAircraftConnection"] &
    df_clean["PreviousArrDelay"].notna() &
    df_clean["TurnaroundMinutes"].notna()
]["DelayVsTurnaround"].describe()

count    504376.000000
mean       -261.125012
std         602.028136
min      -40355.000000
25%        -321.000000
50%         -90.000000
75%         -57.000000
max        1622.000000
Name: DelayVsTurnaround, dtype: float64

In [129]:
turnaround_propagation = (
    df_clean[
        df_clean["ValidAircraftConnection"] &
        df_clean["PreviousDelayBucket"].notna() &
        df_clean["TurnaroundBucket"].notna() &
        df_clean["DepDel15"].notna()
    ]
    .groupby("TurnaroundBucket")["DepDel15"]
    .agg(
        flights="count",
        delayed_departures="sum",
        departure_delay_rate="mean"
    )
    .reset_index()
)

turnaround_propagation

  TurnaroundBucket  flights  delayed_departures  departure_delay_rate
0         0-30 min    11388              4091.0              0.359238
1        31-60 min   150132             32001.0              0.213152
2        61-90 min   134847             18964.0              0.140633
3       91-120 min    42147              8572.0              0.203383
4      121-180 min    22808              6701.0              0.293800
5      181-360 min    19336              4061.0              0.210023
6         360+ min   123688             15151.0              0.122494

In [131]:
propagation_matrix_pivot = propagation_matrix.pivot(
    index="TurnaroundBucket",
    columns="PreviousDelayBucket",
    values="departure_delay_rate"
)

propagation_matrix_pivot

PreviousDelayBucket,Early/On Time,1-14 min,15-30 min,31-60 min,61-120 min,120+ min
TurnaroundBucket,,,,,,
0-30 min,0.063474,0.022995,0.316404,0.827649,0.946916,0.969456
31-60 min,0.034230,0.119104,0.506971,0.843057,0.925937,0.911651
61-90 min,0.048809,0.280825,0.615111,0.779712,0.835418,0.803484
91-120 min,0.147749,0.396772,0.534646,0.581984,0.598837,0.639013
121-180 min,0.253789,0.360431,0.437126,0.470291,0.595707,0.474747
181-360 min,0.204977,0.235689,0.226636,0.198883,0.192130,0.221381
360+ min,0.103625,0.129531,0.146017,0.156496,0.203321,0.267546

In [132]:
high_risk_propagation = df_clean[
    df_clean["ValidAircraftConnection"] &
    df_clean["PreviousDelayBucket"].isin([
        "31-60 min",
        "61-120 min",
        "120+ min"
    ]) &
    df_clean["TurnaroundBucket"].isin([
        "0-30 min",
        "31-60 min"
    ]) &
    df_clean["DepDel15"].notna()
]

In [133]:
airline_propagation = (
    high_risk_propagation
    .groupby("Reporting_Airline")["DepDel15"]
    .agg(
        flights="count",
        delayed_departures="sum",
        departure_delay_rate="mean"
    )
    .reset_index()
)

airline_propagation.sort_values(
    "departure_delay_rate",
    ascending=False
)

   Reporting_Airline  flights  delayed_departures  departure_delay_rate
5                 G4      586               567.0              0.967577
12                WN     4511              4338.0              0.961649
6                 HA      192               182.0              0.947917
8                 NK      599               566.0              0.944908
2                 B6      814               760.0              0.933661
4                 F9      968               897.0              0.926653
3                 DL     2259              2028.0              0.897742
9                 OH     1886              1676.0              0.888653
1                 AS      546               477.0              0.873626
0                 AA     2663              2297.0              0.862561
10                OO     5444              4650.0              0.854151
11                UA     1850              1500.0              0.810811
13                YX     1434              1159.0              0.808229
7                 MQ     1196               942.0              0.787625

In [134]:
airline_baseline = (
    df_clean[
        df_clean["DepDel15"].notna()
    ]
    .groupby("Reporting_Airline")["DepDel15"]
    .agg(
        total_flights="count",
        delayed_departures="sum",
        baseline_delay_rate="mean"
    )
    .reset_index()
)

In [135]:
airline_comparison = airline_propagation.merge(
    airline_baseline,
    on="Reporting_Airline"
)

In [136]:
airline_comparison["PropagationLift"] = (
    airline_comparison["departure_delay_rate"]
    - airline_comparison["baseline_delay_rate"]
)

In [137]:
airline_comparison.sort_values(
    "PropagationLift",
    ascending=False
)

,Reporting_Airline,flights,delayed_departures_x,departure_delay_rate,total_flights,delayed_departures_y,baseline_delay_rate,PropagationLift
6,HA,192,182.0,0.947917,6569,751.0,0.114325,0.833592
12,WN,4511,4338.0,0.961649,102343,17903.0,0.174931,0.786718
8,NK,599,566.0,0.944908,16978,3086.0,0.181765,0.763144
5,G4,586,567.0,0.967577,9227,2175.0,0.235721,0.731856
2,B6,814,760.0,0.933661,17599,3942.0,0.223990,0.709671
1,AS,546,477.0,0.873626,17945,3001.0,0.167233,0.706393
3,DL,2259,2028.0,0.897742,74271,14598.0,0.196550,0.701192
4,F9,968,897.0,0.926653,15142,3515.0,0.232136,0.694517
13,YX,1434,1159.0,0.808229,26732,3279.0,0.122662,0.685567
0,AA,2663,2297.0,0.862561,72348,13598.0,0.187953,0.674608
10,OO,5444,4650.0,0.854151,63716,11923.0,0.187127,0.667024
9,OH,1886,1676.0,0.888653,19219,4456.0,0.231854,0.656799
11,UA,1850,1500.0,0.810811,60856,10136.0,0.166557,0.644254
7,MQ,1196,942.0,0.787625,20879,3297.0,0.157910,0.629716

In [138]:
import os

files = [
    f for f in os.listdir()
    if f.endswith(".csv")
]

len(files), files

(16,
 ['customer_shopping_behavior.csv',
  'HR_Analytics.csv',
  'HR_Analytics_Cleaned.csv',
  'HR_Analytics_Final.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv'])

In [139]:
flight_files = [
    f for f in os.listdir()
    if f.startswith("On_Time_Reporting_Carrier")
    and f.endswith(".csv")
]

len(flight_files), flight_files

(12,
 ['On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv',
  'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv'])

In [141]:
df_2025 = pd.concat(
    [pd.read_csv(file) for file in flight_files],
    ignore_index=True
)

C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: CancellationCode, 1: Div1Airport, 2: Div1TailNum, 3: Div2Airport, 4: Div2TailNum, 5: Div3Airport, 6: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum, 2: Div3Airport) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum, 2: Div3Airport, 3: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],
C:\Users\asus\AppData\Local\Temp\ipykernel_4172\2386367028.py:2: DtypeWarning: Columns (0: CancellationCode, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file) for file in flight_files],

In [142]:
df_2025.shape

(7001619, 110)

In [143]:
df_2025["Month"].value_counts().sort_index()

Month
1     539747
2     504884
3     600872
4     583950
5     605648
6     611575
7     631428
8     602378
9     562439
10    605844
11    570550
12    582304
Name: count, dtype: int64

In [144]:
df_2025_clean = df_2025.copy()

In [145]:
df_2025_clean = df_2025_clean.dropna(axis=1, how="all")

In [146]:
df_2025_clean.shape

(7001619, 93)

In [147]:
df_2025_clean.isna().mean().sort_values(
    ascending=False
).head(25)

Div3TailNum             1.000000
Div3WheelsOff           1.000000
Div3AirportID           0.999999
Div3Airport             0.999999
Div3AirportSeqID        0.999999
Div3LongestGTime        0.999999
Div3TotalGTime          0.999999
Div3WheelsOn            0.999999
Div2TailNum             0.999985
Div2WheelsOff           0.999985
Div2AirportID           0.999971
Div2Airport             0.999971
Div2AirportSeqID        0.999971
Div2LongestGTime        0.999971
Div2TotalGTime          0.999971
Div2WheelsOn            0.999971
DivArrDelay             0.997497
DivActualElapsedTime    0.997497
Div1TailNum             0.997481
Div1WheelsOff           0.997480
DivDistance             0.997249
DivReachedDest          0.997249
Div1AirportID           0.997148
Div1Airport             0.997148
Div1WheelsOn            0.997148
dtype: float64

In [148]:
diversion_detail_cols = [
    col for col in df_2025_clean.columns
    if col.startswith("Div1") or
       col.startswith("Div2") or
       col.startswith("Div3")
]

In [149]:
len(diversion_detail_cols)

24

In [150]:
df_2025_clean = df_2025_clean.drop(columns=diversion_detail_cols)

In [151]:
df_2025_clean.shape

(7001619, 69)

In [152]:
df_2025_clean.columns.tolist()

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'Dest',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'CRSDepTime',
 'DepTime',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrTime',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'ArrivalDelayGroups',
 'ArrTimeBlk',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'DistanceGroup',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'TotalAddGTime',
 'LongestAddGTime',
 'DivAirportLandings',
 'DivReachedDest',
 'DivActualElapsedTime',
 'DivArrDelay',
 'DivDistance']

In [153]:
important_cols = [
    "FlightDate",
    "Reporting_Airline",
    "Tail_Number",
    "Origin",
    "Dest",
    "DepTime",
    "ArrTime",
    "DepDelay",
    "ArrDelay",
    "DepDel15",
    "ArrDel15",
    "CarrierDelay",
    "WeatherDelay",
    "NASDelay",
    "SecurityDelay",
    "LateAircraftDelay",
    "Cancelled",
    "Diverted"
]

df_2025_clean[important_cols].isna().mean().sort_values(
    ascending=False
)

NASDelay             0.780817
SecurityDelay        0.780817
CarrierDelay         0.780817
LateAircraftDelay    0.780817
WeatherDelay         0.780817
ArrDelay             0.017444
ArrDel15             0.017444
ArrTime              0.014941
DepDelay             0.014081
DepDel15             0.014081
DepTime              0.014021
Tail_Number          0.001785
Reporting_Airline    0.000000
FlightDate           0.000000
Origin               0.000000
Dest                 0.000000
Cancelled            0.000000
Diverted             0.000000
dtype: float64