In [335]:
# Flight Delay Propagation Analytics — 2025 ETL Pipeline

## Pipeline

### 1. Extract monthly flight CSV files

### 2. Transform and standardize the data

### 3. Validate the transformed data

### 4. Load the cleaned data into PostgreSQL

### 5. Validate the final database

In [336]:
import os
import pandas as pd

print("Python environment ready")
print("Working directory:", os.getcwd())

Python environment ready
Working directory: C:\Users\asus

In [337]:
flight_files = sorted([
    f for f in os.listdir()
    if f.startswith("On_Time_Reporting_Carrier")
    and f.endswith(".csv")
])

print("Number of flight files found:", len(flight_files))

for file in flight_files:
    print(file)

Number of flight files found: 12
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv

In [338]:
def extract_month(file):
    print(f"Reading: {file}")
    
    df = pd.read_csv(file)
    
    print(f"Rows extracted: {len(df):,}")
    print(f"Columns extracted: {len(df.columns)}")
    
    return df

In [339]:
test_df = extract_month(flight_files[0])

Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 539,747
Columns extracted: 110

In [340]:
## Step 2: Transform

In [341]:
### 2.1 Remove unnecessary columns

In [342]:
def remove_unnecessary_columns(df):
    df = df.copy()

    # Columns that are completely empty
    empty_columns = df.columns[df.isna().all()].tolist()

    # Detailed diversion columns that are not needed for our core analysis
    diversion_detail_columns = [
        col for col in df.columns
        if col.startswith(("Div1", "Div2", "Div3"))
    ]

    columns_to_drop = list(set(empty_columns + diversion_detail_columns))

    df = df.drop(columns=columns_to_drop)

    print(f"Columns removed: {len(columns_to_drop)}")
    print(f"Columns remaining: {len(df.columns)}")

    return df

In [343]:
test_transformed = remove_unnecessary_columns(test_df)

Columns removed: 41
Columns remaining: 69

In [344]:
empty_columns = test_df.columns[test_df.isna().all()].tolist()

diversion_detail_columns = [
    col for col in test_df.columns
    if col.startswith(("Div1", "Div2", "Div3"))
]

overlap_columns = [
    col for col in empty_columns
    if col in diversion_detail_columns
]

print("Completely empty columns:", len(empty_columns))
print("Detailed diversion columns:", len(diversion_detail_columns))
print("Overlap:", len(overlap_columns))
print("Unique columns removed:", len(set(empty_columns + diversion_detail_columns)))

print("\nDetailed diversion columns:")
for col in diversion_detail_columns:
    print(col)

Completely empty columns: 25
Detailed diversion columns: 24
Overlap: 8
Unique columns removed: 41

Detailed diversion columns:
Div1Airport
Div1AirportID
Div1AirportSeqID
Div1WheelsOn
Div1TotalGTime
Div1LongestGTime
Div1WheelsOff
Div1TailNum
Div2Airport
Div2AirportID
Div2AirportSeqID
Div2WheelsOn
Div2TotalGTime
Div2LongestGTime
Div2WheelsOff
Div2TailNum
Div3Airport
Div3AirportID
Div3AirportSeqID
Div3WheelsOn
Div3TotalGTime
Div3LongestGTime
Div3WheelsOff
Div3TailNum

In [345]:
### 2.2 Standardize FlightDate

In [346]:
def standardize_flight_date(df):
    df = df.copy()

    df["FlightDate"] = pd.to_datetime(
        df["FlightDate"],
        errors="coerce"
    )

    return df

In [347]:
test_transformed = standardize_flight_date(test_transformed)

print(test_transformed["FlightDate"].dtype)
print(test_transformed["FlightDate"].head())

datetime64[us]
0   2025-01-01
1   2025-01-02
2   2025-01-03
3   2025-01-04
4   2025-01-05
Name: FlightDate, dtype: datetime64[us]

In [348]:
### 2.3 Create Route

In [349]:
def create_route(df):
    df = df.copy()

    df["Route"] = (
        df["Origin"].astype(str)
        + " → "
        + df["Dest"].astype(str)
    )

    return df

In [350]:
test_transformed = create_route(test_transformed)

print(test_transformed["Route"].head())
print("Missing routes:", test_transformed["Route"].isna().sum())

0    JFK → LAX
1    JFK → LAX
2    JFK → LAX
3    JFK → LAX
4    JFK → LAX
Name: Route, dtype: str
Missing routes: 0

In [351]:
### 2.4 Standardize Delay Indicators

In [352]:
def create_delay_indicators(df):
    df = df.copy()

    df["IsDelayedDeparture"] = df["DepDel15"].map({
        1.0: True,
        0.0: False
    })

    df["IsDelayedArrival"] = df["ArrDel15"].map({
        1.0: True,
        0.0: False
    })

    return df

In [353]:
test_transformed = create_delay_indicators(test_transformed)

print(
    test_transformed[
        ["DepDel15", "IsDelayedDeparture", "ArrDel15", "IsDelayedArrival"]
    ].head(10)
)

print("\nDeparture indicator values:")
print(test_transformed["IsDelayedDeparture"].value_counts(dropna=False))

print("\nArrival indicator values:")
print(test_transformed["IsDelayedArrival"].value_counts(dropna=False))

   DepDel15 IsDelayedDeparture  ArrDel15 IsDelayedArrival
0       0.0              False       0.0            False
1       0.0              False       0.0            False
2       0.0              False       0.0            False
3       0.0              False       0.0            False
4       0.0              False       0.0            False
5       0.0              False       0.0            False
6       0.0              False       0.0            False
7       0.0              False       0.0            False
8       0.0              False       0.0            False
9       0.0              False       0.0            False

Departure indicator values:
IsDelayedDeparture
False    428164
True      95660
NaN       15923
Name: count, dtype: int64

Arrival indicator values:
IsDelayedArrival
False    424139
True      98130
NaN       17478
Name: count, dtype: int64

In [354]:
### 2.5 Create Actual Departure and Arrival Timestamps

In [355]:
def create_actual_departure(df):
    df = df.copy()

    dep_time = df["DepTime"].astype("Int64")

    hours = dep_time // 100
    minutes = dep_time % 100

    df["ActualDeparture"] = (
        df["FlightDate"]
        + pd.to_timedelta(hours, unit="h")
        + pd.to_timedelta(minutes, unit="m")
    )

    # Flights without an actual departure time remain missing
    df.loc[dep_time.isna(), "ActualDeparture"] = pd.NaT

    return df

In [356]:
test_transformed = create_actual_departure(test_transformed)

print(
    test_transformed[
        ["FlightDate", "CRSDepTime", "DepTime", "ActualDeparture"]
    ].head(10)
)

print("\nMissing ActualDeparture:", test_transformed["ActualDeparture"].isna().sum())

  FlightDate  CRSDepTime  DepTime     ActualDeparture
0 2025-01-01         659    656.0 2025-01-01 06:56:00
1 2025-01-02         659    652.0 2025-01-02 06:52:00
2 2025-01-03         659    652.0 2025-01-03 06:52:00
3 2025-01-04         700    653.0 2025-01-04 06:53:00
4 2025-01-05         659    655.0 2025-01-05 06:55:00
5 2025-01-06         659    703.0 2025-01-06 07:03:00
6 2025-01-07         700    655.0 2025-01-07 06:55:00
7 2025-01-08         700    652.0 2025-01-08 06:52:00
8 2025-01-09         659    654.0 2025-01-09 06:54:00
9 2025-01-10         700    700.0 2025-01-10 07:00:00

Missing ActualDeparture: 15886

In [357]:
print("Missing DepTime:", test_transformed["DepTime"].isna().sum())
print("Missing ActualDeparture:", test_transformed["ActualDeparture"].isna().sum())

check = test_transformed[
    test_transformed["DepTime"].isna() &
    test_transformed["ActualDeparture"].notna()
]

print("\nRows with missing DepTime but non-missing ActualDeparture:", len(check))

print(
    check[
        ["FlightDate", "DepTime", "ActualDeparture"]
    ].head(20)
)

Missing DepTime: 15886
Missing ActualDeparture: 15886

Rows with missing DepTime but non-missing ActualDeparture: 0
Empty DataFrame
Columns: [FlightDate, DepTime, ActualDeparture]
Index: []

In [358]:
### 2.5.2 Create ActualArrival

In [359]:
def create_actual_arrival(df):
    df = df.copy()

    arr_time = df["ArrTime"].astype("Int64")

    # Start with an empty datetime column
    df["ActualArrival"] = pd.NaT

    # Normal arrival times
    normal_arrival = arr_time.notna() & (arr_time != 2400)

    hours = arr_time // 100
    minutes = arr_time % 100

    df.loc[normal_arrival, "ActualArrival"] = (
        df.loc[normal_arrival, "FlightDate"]
        + pd.to_timedelta(hours[normal_arrival], unit="h")
        + pd.to_timedelta(minutes[normal_arrival], unit="m")
    )

    # BTS uses 2400 to represent midnight at the end of the day
    midnight_arrival = arr_time == 2400

    df.loc[midnight_arrival, "ActualArrival"] = (
        df.loc[midnight_arrival, "FlightDate"] + pd.Timedelta(days=1)
    )

    # Handle flights arriving after midnight
    overnight = (
        df["ActualArrival"].notna()
        & df["ActualDeparture"].notna()
        & (df["ActualArrival"] < df["ActualDeparture"])
    )

    df.loc[overnight, "ActualArrival"] += pd.Timedelta(days=1)

    return df

In [360]:
test_transformed = create_actual_arrival(test_transformed)

print(
    test_transformed[
        ["FlightDate", "DepTime", "ArrTime",
         "ActualDeparture", "ActualArrival"]
    ].head(10)
)

print("\nMissing ArrTime:", test_transformed["ArrTime"].isna().sum())
print("Missing ActualArrival:", test_transformed["ActualArrival"].isna().sum())
print("ArrTime = 2400:", (test_transformed["ArrTime"] == 2400).sum())

overnight_check = (
    test_transformed["ActualArrival"].notna()
    & test_transformed["ActualDeparture"].notna()
    & (test_transformed["ActualArrival"] < test_transformed["ActualDeparture"])
)

print("Arrival still before departure:", overnight_check.sum())

  FlightDate  DepTime  ArrTime     ActualDeparture       ActualArrival
0 2025-01-01    656.0   1013.0 2025-01-01 06:56:00 2025-01-01 10:13:00
1 2025-01-02    652.0   1022.0 2025-01-02 06:52:00 2025-01-02 10:22:00
2 2025-01-03    652.0   1003.0 2025-01-03 06:52:00 2025-01-03 10:03:00
3 2025-01-04    653.0   1016.0 2025-01-04 06:53:00 2025-01-04 10:16:00
4 2025-01-05    655.0   1013.0 2025-01-05 06:55:00 2025-01-05 10:13:00
5 2025-01-06    703.0   1012.0 2025-01-06 07:03:00 2025-01-06 10:12:00
6 2025-01-07    655.0    955.0 2025-01-07 06:55:00 2025-01-07 09:55:00
7 2025-01-08    652.0    943.0 2025-01-08 06:52:00 2025-01-08 09:43:00
8 2025-01-09    654.0    942.0 2025-01-09 06:54:00 2025-01-09 09:42:00
9 2025-01-10    700.0   1000.0 2025-01-10 07:00:00 2025-01-10 10:00:00

Missing ArrTime: 16580
Missing ActualArrival: 16580
ArrTime = 2400: 245
Arrival still before departure: 0

In [361]:
### 2.6 Create Delay Recovery Metrics

In [362]:
def create_delay_recovery(df):
    df = df.copy()

    # Calculate the change in delay between departure and arrival
    df["DelayRecovery"] = df["DepDelay"] - df["ArrDelay"]

    # Classify the result
    df["RecoveryStatus"] = "Not Applicable"

    valid_delay = (
        df["DepDelay"].notna()
        & df["ArrDelay"].notna()
    )

    df.loc[
        valid_delay & (df["DelayRecovery"] > 0),
        "RecoveryStatus"
    ] = "Recovered"

    df.loc[
        valid_delay & (df["DelayRecovery"] < 0),
        "RecoveryStatus"
    ] = "Additional Delay"

    df.loc[
        valid_delay & (df["DelayRecovery"] == 0),
        "RecoveryStatus"
    ] = "Same"

    return df

In [363]:
test_transformed = create_delay_recovery(test_transformed)

print(
    test_transformed[
        ["DepDelay", "ArrDelay", "DelayRecovery", "RecoveryStatus"]
    ].head(10)
)

print("\nRecovery status counts:")
print(test_transformed["RecoveryStatus"].value_counts(dropna=False))

print("\nMissing DelayRecovery:", test_transformed["DelayRecovery"].isna().sum())

   DepDelay  ArrDelay  DelayRecovery    RecoveryStatus
0      -3.0      -7.0            4.0         Recovered
1      -7.0       2.0           -9.0  Additional Delay
2      -7.0     -17.0           10.0         Recovered
3      -7.0     -10.0            3.0         Recovered
4      -4.0      -7.0            3.0         Recovered
5       4.0      -8.0           12.0         Recovered
6      -5.0     -40.0           35.0         Recovered
7      -8.0     -52.0           44.0         Recovered
8      -5.0     -46.0           41.0         Recovered
9       0.0     -35.0           35.0         Recovered

Recovery status counts:
RecoveryStatus
Recovered           384328
Additional Delay    126332
Not Applicable       17478
Same                 11609
Name: count, dtype: int64

Missing DelayRecovery: 17478

In [364]:
### 2.7 Validate Aircraft Identifiers

In [365]:
print("Total flights:", len(test_transformed))
print("Missing Tail_Number:", test_transformed["Tail_Number"].isna().sum())
print("Unique aircraft:", test_transformed["Tail_Number"].nunique())

Total flights: 539747
Missing Tail_Number: 2530
Unique aircraft: 5612

In [366]:
print("\nTail_Number data type:")
print(test_transformed["Tail_Number"].dtype)

print("\nSample Tail_Numbers:")
print(test_transformed["Tail_Number"].dropna().head(10).tolist())

Tail_Number data type:
str

Sample Tail_Numbers:
['N104NN', 'N110AN', 'N106NN', 'N117AN', 'N104NN', 'N105NN', 'N109NN', 'N106NN', 'N105NN', 'N107NN']

In [367]:
### 2.8 Combine Transformations

In [368]:
def transform_flight_data(df):
    df = remove_unnecessary_columns(df)

    # Standardize PostgreSQL-compatible datatype
    if "DivAirportLandings" in df.columns:
        df["DivAirportLandings"] = df["DivAirportLandings"].astype("Int64")

    df = standardize_flight_date(df)
    df = create_route(df)
    df = create_delay_indicators(df)
    df = create_actual_departure(df)
    df = create_actual_arrival(df)
    df = create_delay_recovery(df)

    return df

In [369]:
test_january = transform_flight_data(test_df)

print("Final shape:", test_january.shape)

Columns removed: 41
Columns remaining: 69
Final shape: (539747, 76)

In [370]:
## Step 3: Validate Transformation

In [371]:
### 3.1 Validate Row Count

In [372]:
original_row_count = len(test_df)
transformed_row_count = len(test_january)

print("Original rows:", original_row_count)
print("Transformed rows:", transformed_row_count)
print("Row count preserved:", original_row_count == transformed_row_count)

Original rows: 539747
Transformed rows: 539747
Row count preserved: True

In [373]:
### 3.2 Validate Required Columns

In [374]:
required_columns = [
    "FlightDate",
    "Reporting_Airline",
    "Tail_Number",
    "Origin",
    "Dest",
    "DepDelay",
    "ArrDelay",
    "DepDel15",
    "ArrDel15",
    "Cancelled",
    "Diverted",
    "Route",
    "IsDelayedDeparture",
    "IsDelayedArrival",
    "ActualDeparture",
    "ActualArrival",
    "DelayRecovery",
    "RecoveryStatus"
]

missing_required_columns = [
    col for col in required_columns
    if col not in test_january.columns
]

print("Missing required columns:", missing_required_columns)
print("All required columns present:", len(missing_required_columns) == 0)

Missing required columns: []
All required columns present: True

In [375]:
### 3.3 Validate Duplicate Rows

In [376]:
duplicate_count = test_january.duplicated().sum()

print("Duplicate rows:", duplicate_count)
print("No duplicates:", duplicate_count == 0)

Duplicate rows: 0
No duplicates: True

In [377]:
### 3.4 Validate Flight Dates

In [378]:
print("Minimum FlightDate:", test_january["FlightDate"].min())
print("Maximum FlightDate:", test_january["FlightDate"].max())

print(
    "January dates only:",
    test_january["FlightDate"].dt.month.eq(1).all()
)

Minimum FlightDate: 2025-01-01 00:00:00
Maximum FlightDate: 2025-01-31 00:00:00
January dates only: True

In [379]:
### 3.5 Validate Flight Timestamps

In [380]:
missing_departure_timestamp = (
    test_january["DepTime"].notna()
    & test_january["ActualDeparture"].isna()
).sum()

missing_arrival_timestamp = (
    test_january["ArrTime"].notna()
    & test_january["ActualArrival"].isna()
).sum()

arrival_before_departure = (
    test_january["ActualArrival"].notna()
    & test_january["ActualDeparture"].notna()
    & (test_january["ActualArrival"] < test_january["ActualDeparture"])
).sum()

print("Flights with DepTime but missing ActualDeparture:", missing_departure_timestamp)
print("Flights with ArrTime but missing ActualArrival:", missing_arrival_timestamp)
print("Flights with arrival before departure:", arrival_before_departure)

Flights with DepTime but missing ActualDeparture: 0
Flights with ArrTime but missing ActualArrival: 0
Flights with arrival before departure: 0

In [381]:
### 3.6 Validate Delay Indicators

In [382]:
departure_delay_check = (
    (test_january["DepDelay"] >= 15)
    == (test_january["DepDel15"] == 1)
)

arrival_delay_check = (
    (test_january["ArrDelay"] >= 15)
    == (test_january["ArrDel15"] == 1)
)

print("Departure delay indicator consistent:", departure_delay_check.all())
print("Arrival delay indicator consistent:", arrival_delay_check.all())

Departure delay indicator consistent: True
Arrival delay indicator consistent: True

In [383]:
### 3.7 Validate Delay Recovery

In [384]:
recovery_check = (
    test_january["DepDelay"].notna()
    & test_january["ArrDelay"].notna()
)

calculated_recovery = (
    test_january.loc[recovery_check, "DepDelay"]
    - test_january.loc[recovery_check, "ArrDelay"]
)

stored_recovery = test_january.loc[
    recovery_check, "DelayRecovery"
]

print(
    "DelayRecovery calculation correct:",
    calculated_recovery.equals(stored_recovery)
)

print("\nRecovery status values:")
print(test_january["RecoveryStatus"].value_counts())

DelayRecovery calculation correct: True

Recovery status values:
RecoveryStatus
Recovered           384328
Additional Delay    126332
Not Applicable       17478
Same                 11609
Name: count, dtype: int64

In [385]:
# Step 4: Process Full 2025 Dataset

In [386]:
## 4.1 Process Monthly Files Automatically

In [387]:
def process_month(file):
    print(f"\nProcessing: {file}")

    # Extract
    raw_df = extract_month(file)

    # Transform
    transformed_df = transform_flight_data(raw_df)

    # Basic validation
    validation = {
        "file": file,
        "rows": len(transformed_df),
        "columns": len(transformed_df.columns),
        "missing_tail_number": transformed_df["Tail_Number"].isna().sum(),
        "duplicates": transformed_df.duplicated().sum(),
        "min_date": transformed_df["FlightDate"].min(),
        "max_date": transformed_df["FlightDate"].max()
    }

    return transformed_df, validation

In [388]:
january_test, january_validation = process_month(flight_files[0])

print("\nJanuary validation:")
print(january_validation)

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 539,747
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

January validation:
{'file': 'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv', 'rows': 539747, 'columns': 76, 'missing_tail_number': np.int64(2530), 'duplicates': np.int64(0), 'min_date': Timestamp('2025-01-01 00:00:00'), 'max_date': Timestamp('2025-01-31 00:00:00')}

In [389]:
### 4.1.2 Process All 12 Months

In [390]:
import re

flight_files = sorted(
    [
        f for f in os.listdir()
        if f.startswith("On_Time_Reporting_Carrier")
        and f.endswith(".csv")
    ],
    key=lambda f: int(re.search(r"_2025_(\d+)\.csv$", f).group(1))
)

for file in flight_files:
    month = int(re.search(r"_2025_(\d+)\.csv$", file).group(1))
    print(f"Month {month}: {file}")

Month 1: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
Month 2: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
Month 3: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
Month 4: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
Month 5: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
Month 6: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
Month 7: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
Month 8: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
Month 9: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv
Month 10: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
Month 11: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
Month 12: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv

In [391]:
expected_rows = {
    1: 539747,
    2: 504884,
    3: 600872,
    4: 583950,
    5: 605648,
    6: 611575,
    7: 631428,
    8: 602378,
    9: 562439,
    10: 605844,
    11: 570550,
    12: 582304
}

all_validations = []

for file in flight_files:

    month = int(re.search(r"_2025_(\d+)\.csv$", file).group(1))

    transformed_df, validation = process_month(file)

    # Validate expected row count for this month
    validation["expected_rows"] = expected_rows[month]
    validation["row_count_correct"] = (
        validation["rows"] == expected_rows[month]
    )

    # Validate that the file contains the expected month
    validation["month_correct"] = (
        transformed_df["FlightDate"].dt.month.eq(month).all()
    )

    all_validations.append(validation)

    # Release this month's DataFrame before processing the next month
    del transformed_df

print("\nFull-year ETL processing completed.")

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 539,747
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum, 2: Div3Airport) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 504,884
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 600,872
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 583,950
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 605,648
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum, 2: Div3Airport, 3: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 611,575
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 631,428
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 602,378
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: CancellationCode, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 562,439
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 605,844
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 570,550
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: CancellationCode, 1: Div1Airport, 2: Div1TailNum, 3: Div2Airport, 4: Div2TailNum, 5: Div3Airport, 6: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 582,304
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Full-year ETL processing completed.

In [392]:
## 4.2 Review Monthly ETL Validation

In [393]:
validation_df = pd.DataFrame(all_validations)

validation_df

,file,rows,columns,missing_tail_number,duplicates,min_date,max_date,expected_rows,row_count_correct,month_correct
0,On_Time_Reporting_Carrier_On_Time_Performance_...,539747,76,2530,0,2025-01-01,2025-01-31,539747,True,True
1,On_Time_Reporting_Carrier_On_Time_Performance_...,504884,76,804,0,2025-02-01,2025-02-28,504884,True,True
2,On_Time_Reporting_Carrier_On_Time_Performance_...,600872,76,768,0,2025-03-01,2025-03-31,600872,True,True
3,On_Time_Reporting_Carrier_On_Time_Performance_...,583950,76,504,0,2025-04-01,2025-04-30,583950,True,True
4,On_Time_Reporting_Carrier_On_Time_Performance_...,605648,76,732,0,2025-05-01,2025-05-31,605648,True,True
5,On_Time_Reporting_Carrier_On_Time_Performance_...,611575,76,921,0,2025-06-01,2025-06-30,611575,True,True
6,On_Time_Reporting_Carrier_On_Time_Performance_...,631428,76,1694,0,2025-07-01,2025-07-31,631428,True,True
7,On_Time_Reporting_Carrier_On_Time_Performance_...,602378,76,1035,0,2025-08-01,2025-08-31,602378,True,True
8,On_Time_Reporting_Carrier_On_Time_Performance_...,562439,76,219,0,2025-09-01,2025-09-30,562439,True,True
9,On_Time_Reporting_Carrier_On_Time_Performance_...,605844,76,293,0,2025-10-01,2025-10-31,605844,True,True
10,On_Time_Reporting_Carrier_On_Time_Performance_...,570550,76,2148,0,2025-11-01,2025-11-30,570550,True,True
11,On_Time_Reporting_Carrier_On_Time_Performance_...,582304,76,853,0,2025-12-01,2025-12-31,582304,True,True

In [394]:
print("Months processed:", len(validation_df))

print(
    "All row counts correct:",
    validation_df["row_count_correct"].all()
)

print(
    "All months correct:",
    validation_df["month_correct"].all()
)

print(
    "Total rows processed:",
    validation_df["rows"].sum()
)

print(
    "Total expected rows:",
    validation_df["expected_rows"].sum()
)

print(
    "Total row count matches:",
    validation_df["rows"].sum() == validation_df["expected_rows"].sum()
)

print(
    "Total duplicate rows:",
    validation_df["duplicates"].sum()
)

Months processed: 12
All row counts correct: True
All months correct: True
Total rows processed: 7001619
Total expected rows: 7001619
Total row count matches: True
Total duplicate rows: 0

In [395]:
### 4.3 Full Transformation Quality Gate

In [396]:
def validate_transformed_data(df, expected_month=None):
    checks = {}

    # Required columns
    required_columns = [
        "FlightDate",
        "Reporting_Airline",
        "Tail_Number",
        "Origin",
        "Dest",
        "DepDelay",
        "ArrDelay",
        "DepDel15",
        "ArrDel15",
        "Cancelled",
        "Diverted",
        "Route",
        "IsDelayedDeparture",
        "IsDelayedArrival",
        "ActualDeparture",
        "ActualArrival",
        "DelayRecovery",
        "RecoveryStatus"
    ]

    checks["required_columns_present"] = all(
        col in df.columns for col in required_columns
    )

    # Duplicate rows
    checks["duplicates"] = df.duplicated().sum()

    # Date validation
    checks["flight_date_missing"] = df["FlightDate"].isna().sum()

    if expected_month is not None:
        checks["month_correct"] = (
            df["FlightDate"].dt.month.eq(expected_month).all()
        )
    else:
        checks["month_correct"] = True

    # Timestamp validation
    checks["invalid_departure_timestamp"] = (
        df["DepTime"].notna()
        & df["ActualDeparture"].isna()
    ).sum()

    checks["invalid_arrival_timestamp"] = (
        df["ArrTime"].notna()
        & df["ActualArrival"].isna()
    ).sum()

    checks["arrival_before_departure"] = (
        df["ActualArrival"].notna()
        & df["ActualDeparture"].notna()
        & (df["ActualArrival"] < df["ActualDeparture"])
    ).sum()

    # Delay indicator validation
    checks["departure_delay_indicator_correct"] = (
        (df["DepDelay"] >= 15)
        == (df["DepDel15"] == 1)
    ).all()

    checks["arrival_delay_indicator_correct"] = (
        (df["ArrDelay"] >= 15)
        == (df["ArrDel15"] == 1)
    ).all()

    # Recovery calculation
    valid_delay = (
        df["DepDelay"].notna()
        & df["ArrDelay"].notna()
    )

    checks["delay_recovery_correct"] = (
        df.loc[valid_delay, "DelayRecovery"]
        == (
            df.loc[valid_delay, "DepDelay"]
            - df.loc[valid_delay, "ArrDelay"]
        )
    ).all()

    return checks

In [397]:
january_quality = validate_transformed_data(
    test_january,
    expected_month=1
)

january_quality

{'required_columns_present': True,
 'duplicates': np.int64(0),
 'flight_date_missing': np.int64(0),
 'month_correct': np.True_,
 'invalid_departure_timestamp': np.int64(0),
 'invalid_arrival_timestamp': np.int64(0),
 'arrival_before_departure': np.int64(0),
 'departure_delay_indicator_correct': np.True_,
 'arrival_delay_indicator_correct': np.True_,
 'delay_recovery_correct': np.True_}

In [398]:
def process_month(file, expected_month):
    print(f"\nProcessing: {file}")

    # Extract
    raw_df = extract_month(file)

    # Transform
    transformed_df = transform_flight_data(raw_df)

    # Validate
    quality = validate_transformed_data(
        transformed_df,
        expected_month=expected_month
    )

    # Basic validation
    quality["rows"] = len(transformed_df)
    quality["columns"] = len(transformed_df.columns)
    quality["missing_tail_number"] = transformed_df["Tail_Number"].isna().sum()

    return transformed_df, quality

In [399]:
january_test, january_quality = process_month(
    flight_files[0],
    expected_month=1
)

print("\nJanuary quality check:")
print(january_quality)

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 539,747
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

January quality check:
{'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 539747, 'columns': 76, 'missing_tail_number': np.int64(2530)}

In [400]:
full_year_quality = []

for file in flight_files:

    month = int(
        re.search(r"_2025_(\d+)\.csv$", file).group(1)
    )

    transformed_df, quality = process_month(
        file,
        expected_month=month
    )

    full_year_quality.append(quality)

    # Release the month's DataFrame before processing the next month
    del transformed_df

print("\nFull-year quality-gated ETL completed.")

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 539,747
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum, 2: Div3Airport) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 504,884
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 600,872
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 583,950
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 605,648
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum, 2: Div3Airport, 3: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 611,575
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 631,428
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 602,378
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: CancellationCode, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 562,439
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 605,844
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 570,550
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: CancellationCode, 1: Div1Airport, 2: Div1TailNum, 3: Div2Airport, 4: Div2TailNum, 5: Div3Airport, 6: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 582,304
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Full-year quality-gated ETL completed.

In [401]:
### 4.4 Review Full-Year Quality Results

In [402]:
full_year_quality_df = pd.DataFrame(full_year_quality)

full_year_quality_df

,required_columns_present,duplicates,flight_date_missing,month_correct,invalid_departure_timestamp,invalid_arrival_timestamp,arrival_before_departure,departure_delay_indicator_correct,arrival_delay_indicator_correct,delay_recovery_correct,rows,columns,missing_tail_number
0,True,0,0,True,0,0,0,True,True,True,539747,76,2530
1,True,0,0,True,0,0,0,True,True,True,504884,76,804
2,True,0,0,True,0,0,0,True,True,True,600872,76,768
3,True,0,0,True,0,0,0,True,True,True,583950,76,504
4,True,0,0,True,0,0,0,True,True,True,605648,76,732
5,True,0,0,True,0,0,0,True,True,True,611575,76,921
6,True,0,0,True,0,0,0,True,True,True,631428,76,1694
7,True,0,0,True,0,0,0,True,True,True,602378,76,1035
8,True,0,0,True,0,0,0,True,True,True,562439,76,219
9,True,0,0,True,0,0,0,True,True,True,605844,76,293
10,True,0,0,True,0,0,0,True,True,True,570550,76,2148
11,True,0,0,True,0,0,0,True,True,True,582304,76,853

In [403]:
print("Months processed:", len(full_year_quality_df))

print(
    "Required columns present:",
    full_year_quality_df["required_columns_present"].all()
)

print(
    "All months correct:",
    full_year_quality_df["month_correct"].all()
)

print(
    "Total duplicate rows:",
    full_year_quality_df["duplicates"].sum()
)

print(
    "Total missing FlightDate:",
    full_year_quality_df["flight_date_missing"].sum()
)

print(
    "Invalid departure timestamps:",
    full_year_quality_df["invalid_departure_timestamp"].sum()
)

print(
    "Invalid arrival timestamps:",
    full_year_quality_df["invalid_arrival_timestamp"].sum()
)

print(
    "Arrival before departure:",
    full_year_quality_df["arrival_before_departure"].sum()
)

print(
    "Departure delay checks:",
    full_year_quality_df["departure_delay_indicator_correct"].all()
)

print(
    "Arrival delay checks:",
    full_year_quality_df["arrival_delay_indicator_correct"].all()
)

print(
    "Delay recovery checks:",
    full_year_quality_df["delay_recovery_correct"].all()
)

print(
    "Total rows processed:",
    full_year_quality_df["rows"].sum()
)

Months processed: 12
Required columns present: True
All months correct: True
Total duplicate rows: 0
Total missing FlightDate: 0
Invalid departure timestamps: 0
Invalid arrival timestamps: 0
Arrival before departure: 0
Departure delay checks: True
Arrival delay checks: True
Delay recovery checks: True
Total rows processed: 7001619

In [404]:
# Step 5: Load Data into PostgreSQL

In [405]:
## 5.1 Connect to PostgreSQL

In [406]:
import psycopg2
import sqlalchemy

print("psycopg2:", psycopg2.__version__)
print("SQLAlchemy:", sqlalchemy.__version__)

psycopg2: 2.9.13 (dt dec pq3 ext lo64)
SQLAlchemy: 2.0.51

In [407]:
import getpass
from sqlalchemy import create_engine, text

password = getpass.getpass("Enter PostgreSQL password: ")

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/flight_delay_analytics"
)

print("PostgreSQL connection configured.")

Enter PostgreSQL password:  ········

PostgreSQL connection configured.

In [408]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 18.6 on x86_64-windows, compiled by msvc-19.44.35228, 64-bit

In [409]:
# Test PostgreSQL load with January data

jan_df = process_month(flight_files[0], expected_month=1)[0]

print("January rows:", len(jan_df))
print("January columns:", len(jan_df.columns))

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 539,747
Columns extracted: 110
Columns removed: 41
Columns remaining: 69
January rows: 539747
January columns: 76

In [410]:
import io
import csv
import psycopg2

print("Ready for PostgreSQL bulk loading.")

Ready for PostgreSQL bulk loading.

In [411]:
# Create an empty PostgreSQL table using the transformed January schema

jan_df.head(0).to_sql(
    "flights_2025",
    engine,
    if_exists="replace",
    index=False
)

print("Empty flights_2025 table created successfully.")

Empty flights_2025 table created successfully.

In [412]:
# Test PostgreSQL COPY with 10,000 January rows

test_df = jan_df.head(10_000)

buffer = io.StringIO()

test_df.to_csv(
    buffer,
    index=False,
    header=False,
    sep="\t",
    na_rep="\\N",
    quoting=csv.QUOTE_MINIMAL
)

buffer.seek(0)

with engine.raw_connection() as conn:
    with conn.cursor() as cur:
        cur.copy_from(
            buffer,
            "flights_2025",
            sep="\t",
            null="\\N"
        )
    conn.commit()

print("10,000 rows loaded successfully.")

10,000 rows loaded successfully.

In [413]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM flights_2025;")
    )
    print("Rows in PostgreSQL:", result.fetchone()[0])

Rows in PostgreSQL: 10000

In [414]:
# Load the remaining January rows

remaining_df = jan_df.iloc[10_000:]

buffer = io.StringIO()

remaining_df.to_csv(
    buffer,
    index=False,
    header=False,
    sep="\t",
    na_rep="\\N",
    quoting=csv.QUOTE_MINIMAL
)

buffer.seek(0)

with engine.raw_connection() as conn:
    with conn.cursor() as cur:
        cur.copy_from(
            buffer,
            "flights_2025",
            sep="\t",
            null="\\N"
        )
    conn.commit()

print(f"Loaded {len(remaining_df):,} remaining January rows.")

Loaded 529,747 remaining January rows.

In [415]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM flights_2025;")
    )
    print("Total rows in PostgreSQL:", result.fetchone()[0])

Total rows in PostgreSQL: 539747

In [416]:
def load_dataframe_to_postgres(df, table_name, engine):
    """
    Bulk-load a DataFrame into PostgreSQL using COPY.
    """

    buffer = io.StringIO()

    df.to_csv(
        buffer,
        index=False,
        header=False,
        sep="\t",
        na_rep="\\N",
        quoting=csv.QUOTE_MINIMAL
    )

    buffer.seek(0)

    with engine.raw_connection() as conn:
        with conn.cursor() as cur:
            cur.copy_from(
                buffer,
                table_name,
                sep="\t",
                null="\\N"
            )
        conn.commit()

    return len(df)

In [417]:
# Process February
feb_df, feb_quality = process_month(
    flight_files[1],
    expected_month=2
)

print("February rows:", len(feb_df))
print("February columns:", len(feb_df.columns))
print("Quality checks:", feb_quality)

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum, 2: Div3Airport) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 504,884
Columns extracted: 110
Columns removed: 41
Columns remaining: 69
February rows: 504884
February columns: 76
Quality checks: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 504884, 'columns': 76, 'missing_tail_number': np.int64(804)}

In [418]:
loaded_rows = load_dataframe_to_postgres(
    feb_df,
    "flights_2025",
    engine
)

print(f"February rows loaded: {loaded_rows:,}")

February rows loaded: 504,884

In [419]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM flights_2025;")
    )
    print("Total rows in PostgreSQL:", result.fetchone()[0])

Total rows in PostgreSQL: 1044631

In [420]:
march_df, march_quality = process_month(
    flight_files[2],
    expected_month=3
)

print("March rows:", len(march_df))
print("March columns:", len(march_df.columns))
print("Quality checks:", march_quality)

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 600,872
Columns extracted: 110
Columns removed: 41
Columns remaining: 69
March rows: 600872
March columns: 76
Quality checks: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 600872, 'columns': 76, 'missing_tail_number': np.int64(768)}

In [421]:
loaded_rows = load_dataframe_to_postgres(
    march_df,
    "flights_2025",
    engine
)

print(f"March rows loaded: {loaded_rows:,}")

March rows loaded: 600,872

In [422]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM flights_2025;")
    )
    print("Total rows in PostgreSQL:", result.fetchone()[0])

Total rows in PostgreSQL: 1645503

In [423]:
# Process April and May

april_df, april_quality = process_month(
    flight_files[3],
    expected_month=4
)

may_df, may_quality = process_month(
    flight_files[4],
    expected_month=5
)

print("\n--- April ---")
print("Rows:", len(april_df))
print("Quality:", april_quality)

print("\n--- May ---")
print("Rows:", len(may_df))
print("Quality:", may_quality)

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 583,950
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 605,648
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

--- April ---
Rows: 583950
Quality: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 583950, 'columns': 76, 'missing_tail_number': np.int64(504)}

--- May ---
Rows: 605648
Quality: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 605648, 'columns': 76, 'missing_tail_number': np.int64(732)}

In [424]:
# Load April and May into PostgreSQL

april_loaded = load_dataframe_to_postgres(
    april_df,
    "flights_2025",
    engine
)

may_loaded = load_dataframe_to_postgres(
    may_df,
    "flights_2025",
    engine
)

print(f"April loaded: {april_loaded:,}")
print(f"May loaded: {may_loaded:,}")

April loaded: 583,950
May loaded: 605,648

In [425]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM flights_2025;")
    )
    print("Total rows in PostgreSQL:", result.fetchone()[0])

Total rows in PostgreSQL: 2835101

In [426]:
# Process June, July and August

june_df, june_quality = process_month(
    flight_files[5],
    expected_month=6
)

july_df, july_quality = process_month(
    flight_files[6],
    expected_month=7
)

august_df, august_quality = process_month(
    flight_files[7],
    expected_month=8
)

print("\n--- June ---")
print("Rows:", len(june_df))
print("Quality:", june_quality)

print("\n--- July ---")
print("Rows:", len(july_df))
print("Quality:", july_quality)

print("\n--- August ---")
print("Rows:", len(august_df))
print("Quality:", august_quality)

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum, 2: Div3Airport, 3: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 611,575
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 631,428
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 602,378
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

--- June ---
Rows: 611575
Quality: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 611575, 'columns': 76, 'missing_tail_number': np.int64(921)}

--- July ---
Rows: 631428
Quality: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 631428, 'columns': 76, 'missing_tail_number': np.int64(1694)}

--- August ---
Rows: 602378
Quality: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 602378, 'columns': 76, 'missing_tail_number': np.int64(1035)}

In [427]:
# Load June, July and August into PostgreSQL

june_loaded = load_dataframe_to_postgres(
    june_df,
    "flights_2025",
    engine
)

july_loaded = load_dataframe_to_postgres(
    july_df,
    "flights_2025",
    engine
)

august_loaded = load_dataframe_to_postgres(
    august_df,
    "flights_2025",
    engine
)

print(f"June loaded: {june_loaded:,}")
print(f"July loaded: {july_loaded:,}")
print(f"August loaded: {august_loaded:,}")

June loaded: 611,575
July loaded: 631,428
August loaded: 602,378

In [428]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM flights_2025;")
    )
    print("Total rows in PostgreSQL:", result.fetchone()[0])

Total rows in PostgreSQL: 4680482

In [429]:
# Process September, October, November and December

september_df, september_quality = process_month(
    flight_files[8],
    expected_month=9
)

october_df, october_quality = process_month(
    flight_files[9],
    expected_month=10
)

november_df, november_quality = process_month(
    flight_files[10],
    expected_month=11
)

december_df, december_quality = process_month(
    flight_files[11],
    expected_month=12
)

print("\n--- September ---")
print("Rows:", len(september_df))
print("Quality:", september_quality)

print("\n--- October ---")
print("Rows:", len(october_df))
print("Quality:", october_quality)

print("\n--- November ---")
print("Rows:", len(november_df))
print("Quality:", november_quality)

print("\n--- December ---")
print("Rows:", len(december_df))
print("Quality:", december_quality)

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: CancellationCode, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 562,439
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div1Airport, 1: Div1TailNum, 2: Div2Airport, 3: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 605,844
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: Div2Airport, 1: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 570,550
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv

C:\Users\asus\AppData\Local\Temp\ipykernel_20460\3228930941.py:4: DtypeWarning: Columns (0: CancellationCode, 1: Div1Airport, 2: Div1TailNum, 3: Div2Airport, 4: Div2TailNum, 5: Div3Airport, 6: Div3TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Rows extracted: 582,304
Columns extracted: 110
Columns removed: 41
Columns remaining: 69

--- September ---
Rows: 562439
Quality: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 562439, 'columns': 76, 'missing_tail_number': np.int64(219)}

--- October ---
Rows: 605844
Quality: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 605844, 'columns': 76, 'missing_tail_number': np.int64(293)}

--- November ---
Rows: 570550
Quality: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 570550, 'columns': 76, 'missing_tail_number': np.int64(2148)}

--- December ---
Rows: 582304
Quality: {'required_columns_present': True, 'duplicates': np.int64(0), 'flight_date_missing': np.int64(0), 'month_correct': np.True_, 'invalid_departure_timestamp': np.int64(0), 'invalid_arrival_timestamp': np.int64(0), 'arrival_before_departure': np.int64(0), 'departure_delay_indicator_correct': np.True_, 'arrival_delay_indicator_correct': np.True_, 'delay_recovery_correct': np.True_, 'rows': 582304, 'columns': 76, 'missing_tail_number': np.int64(853)}

In [439]:
# Load September through December into PostgreSQL

september_loaded = load_dataframe_to_postgres(
    september_df,
    "flights_2025",
    engine
)

october_loaded = load_dataframe_to_postgres(
    october_df,
    "flights_2025",
    engine
)

november_loaded = load_dataframe_to_postgres(
    november_df,
    "flights_2025",
    engine
)

december_loaded = load_dataframe_to_postgres(
    december_df,
    "flights_2025",
    engine
)

print(f"September loaded: {september_loaded:,}")
print(f"October loaded: {october_loaded:,}")
print(f"November loaded: {november_loaded:,}")
print(f"December loaded: {december_loaded:,}")

September loaded: 562,439
October loaded: 605,844
November loaded: 570,550
December loaded: 582,304

In [431]:
print(september_df["DivAirportLandings"].dtype)
print(september_df["DivAirportLandings"].value_counts(dropna=False).head(10))

Int64
DivAirportLandings
0       561202
1         1217
9           12
2            7
<NA>         1
Name: count, dtype: Int64

In [432]:
for df in [september_df, october_df, november_df, december_df]:
    df["DivAirportLandings"] = df["DivAirportLandings"].astype("Int64")

print("DivAirportLandings normalized.")
print(september_df["DivAirportLandings"].dtype)

DivAirportLandings normalized.
Int64

In [433]:
# Load September through December into PostgreSQL

september_loaded = load_dataframe_to_postgres(
    september_df,
    "flights_2025",
    engine
)

october_loaded = load_dataframe_to_postgres(
    october_df,
    "flights_2025",
    engine
)

november_loaded = load_dataframe_to_postgres(
    november_df,
    "flights_2025",
    engine
)

december_loaded = load_dataframe_to_postgres(
    december_df,
    "flights_2025",
    engine
)

print(f"September loaded: {september_loaded:,}")
print(f"October loaded: {october_loaded:,}")
print(f"November loaded: {november_loaded:,}")
print(f"December loaded: {december_loaded:,}")

September loaded: 562,439
October loaded: 605,844
November loaded: 570,550
December loaded: 582,304

In [434]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM flights_2025;")
    )
    total_rows = result.fetchone()[0]

print(f"Total rows in PostgreSQL: {total_rows:,}")
print("Expected rows: 7,001,619")
print("Match:", total_rows == 7_001_619)

Total rows in PostgreSQL: 9,322,756
Expected rows: 7,001,619
Match: False

In [435]:
with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            EXTRACT(MONTH FROM "FlightDate")::int AS month,
            COUNT(*) AS rows
        FROM flights_2025
        GROUP BY 1
        ORDER BY 1;
    """))

    for row in result:
        print(f"Month {row[0]:02d}: {row[1]:,} rows")

Month 01: 539,747 rows
Month 02: 504,884 rows
Month 03: 600,872 rows
Month 04: 583,950 rows
Month 05: 605,648 rows
Month 06: 611,575 rows
Month 07: 631,428 rows
Month 08: 602,378 rows
Month 09: 1,124,878 rows
Month 10: 1,211,688 rows
Month 11: 1,141,100 rows
Month 12: 1,164,608 rows

In [437]:
with engine.connect() as connection:
    connection.execute(text("""
        DELETE FROM flights_2025
        WHERE EXTRACT(MONTH FROM "FlightDate") BETWEEN 9 AND 12;
    """))
    connection.commit()

print("September–December duplicate rows removed.")

KeyboardInterrupt:

In [438]:
with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            EXTRACT(MONTH FROM "FlightDate")::int AS month,
            COUNT(*) AS rows
        FROM flights_2025
        GROUP BY 1
        ORDER BY 1;
    """))

    rows_by_month = result.fetchall()

for month, rows in rows_by_month:
    print(f"Month {month:02d}: {rows:,} rows")

print("\nTotal:", f"{sum(rows for _, rows in rows_by_month):,}")

Month 01: 539,747 rows
Month 02: 504,884 rows
Month 03: 600,872 rows
Month 04: 583,950 rows
Month 05: 605,648 rows
Month 06: 611,575 rows
Month 07: 631,428 rows
Month 08: 602,378 rows

Total: 4,680,482

In [440]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM flights_2025;")
    )
    total_rows = result.fetchone()[0]

print(f"Total rows in PostgreSQL: {total_rows:,}")
print(f"Expected rows: {7_001_619:,}")
print("Match:", total_rows == 7_001_619)

Total rows in PostgreSQL: 7,001,619
Expected rows: 7,001,619
Match: True

In [441]:
with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            column_name,
            data_type
        FROM information_schema.columns
        WHERE table_name = 'flights_2025'
        ORDER BY ordinal_position;
    """))

    for row in result:
        print(f"{row[0]:30} {row[1]}")

Year                           bigint
Quarter                        bigint
Month                          bigint
DayofMonth                     bigint
DayOfWeek                      bigint
FlightDate                     timestamp without time zone
Reporting_Airline              text
DOT_ID_Reporting_Airline       bigint
IATA_CODE_Reporting_Airline    text
Tail_Number                    text
Flight_Number_Reporting_Airline bigint
OriginAirportID                bigint
OriginAirportSeqID             bigint
OriginCityMarketID             bigint
Origin                         text
OriginCityName                 text
OriginState                    text
OriginStateFips                bigint
OriginStateName                text
OriginWac                      bigint
DestAirportID                  bigint
DestAirportSeqID               bigint
DestCityMarketID               bigint
Dest                           text
DestCityName                   text
DestState                      text
DestStateFips                  bigint
DestStateName                  text
DestWac                        bigint
CRSDepTime                     bigint
DepTime                        double precision
DepDelay                       double precision
DepDelayMinutes                double precision
DepDel15                       double precision
DepartureDelayGroups           double precision
DepTimeBlk                     text
TaxiOut                        double precision
WheelsOff                      double precision
WheelsOn                       double precision
TaxiIn                         double precision
CRSArrTime                     bigint
ArrTime                        double precision
ArrDelay                       double precision
ArrDelayMinutes                double precision
ArrDel15                       double precision
ArrivalDelayGroups             double precision
ArrTimeBlk                     text
Cancelled                      double precision
CancellationCode               text
Diverted                       double precision
CRSElapsedTime                 double precision
ActualElapsedTime              double precision
AirTime                        double precision
Flights                        double precision
Distance                       double precision
DistanceGroup                  bigint
CarrierDelay                   double precision
WeatherDelay                   double precision
NASDelay                       double precision
SecurityDelay                  double precision
LateAircraftDelay              double precision
FirstDepTime                   double precision
TotalAddGTime                  double precision
LongestAddGTime                double precision
DivAirportLandings             bigint
DivReachedDest                 double precision
DivActualElapsedTime           double precision
DivArrDelay                    double precision
DivDistance                    double precision
Route                          text
IsDelayedDeparture             text
IsDelayedArrival               text
ActualDeparture                timestamp without time zone
ActualArrival                  timestamp without time zone
DelayRecovery                  double precision
RecoveryStatus                 text